#!/bin/sh
# test_reconcile_matcher.sh — ONE matcher, two callers, and the parameters
# that separate them (14z-95, GitHub #43(a), maintainer-ruled 2026-08-18).
#
# tools/reconcile_batch.py carried a COPY of tools/find_equiv.py's core, and
# the copy had drifted three ways: no relaxed-anchor fallback, a 64-hit cap
# applied BEFORE the score sort (so it keeps the first 64 by ADDRESS, not the
# best 64), and `return []` where find_equiv exits on an unusable window. The
# human-facing tool and the machine one therefore gave DIFFERENT ANSWERS for
# the same input, and 357 committed rows were generated by the drifted one.
#
# THE SPLIT THIS GATE POLICES. The maintainer split #43 on the line between
# what moves bytes and what does not:
#   (a) the refactor, pinned to the batch tool's measured parameters
#       (HIT_CAP=64, ALLOW_FALLBACK=False) — provably inert, landed.
#   (b) freeing those parameters — re-resolves rows, moves built bytes, rides
#       the next re-freeze under rule 6. NOT landed.
# So section 2 asserts inertness and section 3 asserts the parameters are
# load-bearing. Both are required: without 2 the refactor could have moved a
# row; without 3 the parameterisation could be decoration wired to nothing.
#
# WHY THE OBVIOUS CONTROL WOULD PROVE NOTHING. reconcile_batch KEEPS existing
# rows ("existing rows win"), so re-running it against the committed manifest
# reproduces all 328 rows no matter which matcher is installed. A green
# re-emit is not evidence. The comparison has to be at the MATCHER, against
# the pre-refactor copy reconstructed from git.
#
# ROMDIR + git history. ~4 min (two decrypts + 3280 masked searches).
set -eu
REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"
ROMDIR="${ROMDIR:?set ROMDIR}"
BASE="${RECONCILE_BASE_REV:-}"

W="$(mktemp -d)"; trap 'rm -rf "$W"' EXIT
fail=0
ok()  { echo "  ok: $1"; }
bad() { echo "FAIL: $1"; fail=1; }

echo "== 1: there is ONE implementation"
if grep -q "^def masked_search" tools/find_equiv.py; then
    ok "find_equiv.py owns masked_search"
else
    bad "find_equiv.py no longer defines masked_search"
fi
if grep -q "^def masked_search" tools/reconcile_batch.py; then
    bad "reconcile_batch.py has re-grown its own masked_search — that is the copy #43 deleted"
else
    ok "reconcile_batch.py defines no matcher of its own"
fi
grep -q "^import find_equiv" tools/reconcile_batch.py \
    && ok "reconcile_batch imports the canonical matcher" \
    || bad "reconcile_batch does not import find_equiv"
# the algorithm must not be pasted back in under another name
for marker in "dst_img.find(anchor" "mask.count(1)"; do
    if grep -q "$marker" tools/reconcile_batch.py; then
        bad "reconcile_batch contains matcher internals ('$marker') — a renamed copy is still a copy"
    fi
done
ok "no matcher internals in the batch tool"

echo "== 2: pinned parameters are INERT vs the pre-refactor copy"
# Reconstruct the drifted copy from the last commit that still had it. The
# revision is DERIVED, not pinned to a hash, so this keeps working as history
# grows; RECONCILE_BASE_REV overrides it.
if [ -z "$BASE" ]; then
    BASE="$(git log --format=%H -S 'def masked_search' -- tools/reconcile_batch.py \
            | head -1)"
fi
if [ -z "$BASE" ] || ! git show "$BASE:tools/reconcile_batch.py" > "$W/rb_old.py" 2>/dev/null; then
    echo "  SKIP: cannot reconstruct the pre-refactor copy from git"
else
    git show "$BASE:tools/reconcile_batch.py" > "$W/rb_old.py"
    if grep -q "^def masked_search" "$W/rb_old.py"; then
        ok "reconstructed the drifted copy from $(echo "$BASE" | cut -c1-8)"
        if python3 tests/lib/cmp_matchers.py "$ROMDIR" "$W/rb_old.py"; then
            ok "pinned parameters reproduce the drifted copy on every probe"
        else
            bad "the refactor MOVED a result — this is a rule-6 finding."
            echo "     Do not adjust rows to make this green; attribute it."
        fi
        # MUST-FIRE: "1640 of 1640 identical" is equally consistent with a
        # comparison that cannot detect anything at all. Perturb the binding
        # and require the same comparison to go red.
        if python3 tests/lib/cmp_matchers.py "$ROMDIR" "$W/rb_old.py" --control; then
            ok "control: the comparison DOES detect a moved result"
        else
            bad "control did not fire — section 2's result proves nothing"
        fi
    else
        echo "  SKIP: $BASE has no masked_search to compare against"
    fi
fi

echo "== 3: the parameters are LOAD-BEARING, not decoration"
# NB the helper exits 0 when the flags DO change results — "no difference" is
# the failure here, because a flag wired to nothing would make #43(b) a no-op
# and section 2's inertness result meaningless (everything is inert if nothing
# is connected).
if python3 tests/lib/cmp_matchers.py "$ROMDIR" --free; then
    ok "freeing the parameters changes results (so #43(b) is a real change)"
else
    bad "freeing hit_cap/allow_fallback changed NOTHING — the flags are dead,"
    echo "     which would make #43(b) a no-op and section 2 vacuous"
fi
python3 - <<'PYCHK' || bad "reconcile_batch is not pinned to its measured values"
import sys
sys.path.insert(0, "tools")
import reconcile_batch as rb
assert rb.HIT_CAP == 64, rb.HIT_CAP
assert rb.ALLOW_FALLBACK is False, rb.ALLOW_FALLBACK
print("  ok: reconcile_batch pinned at HIT_CAP=64, ALLOW_FALLBACK=False")
PYCHK

echo "== 4: an unusable window is DISTINGUISHABLE from no candidate (drift c)"
python3 - <<'PYCHK' || bad "the unusable-window signal is missing or wrong"
import sys
sys.path.insert(0, "tools")
import find_equiv, reconcile_batch
# Three `jsr $00028DD8` in a row: 18 bytes of which 12 are wildcarded
# operands, leaving 6 must-match — under the 8-byte floor. Sized
# deliberately: four of these would leave 8 hard bytes and NOT trip it, so
# a fixture that merely "looks operand-heavy" would test nothing.
src = bytes.fromhex("4eb900028dd8") * 3
dst = b"\x00" * 0x400
try:
    find_equiv.masked_search(src, dst, 0, 0x12)
except find_equiv.WindowUnusable as e:
    assert "operands" in str(e), e
    print("  ok: find_equiv RAISES WindowUnusable and names the reason")
else:
    sys.exit("find_equiv did not raise on an all-operand window")
# the batch tool converts it to [] on purpose (it retries other windows)
assert reconcile_batch._batch_search(src, dst, 0, 0x12) == []
print("  ok: the batch tool absorbs it as [] (it retries other window sizes)")
PYCHK

echo "== 5: the --allow-plausible claim matches reality"
# The docstring said "for experiment builds only" while build_merged.sh
# hardcodes it, so plausible rows ship in the artifact that gets played.
if grep -q "allow-plausible exists for experiment builds only" tools/reconcile_batch.py; then
    bad "the retracted '--allow-plausible is experiment-only' claim is back"
else
    ok "the experiment-only claim is not asserted"
fi
if grep -q -- "--allow-plausible" tools/build_merged.sh; then
    grep -q "PLAUSIBLE ROWS SHIP" tools/reconcile_batch.py \
        && ok "build_merged hardcodes it, and reconcile_batch says so" \
        || bad "build_merged hardcodes --allow-plausible and nothing records it"
else
    ok "build_merged no longer hardcodes --allow-plausible"
fi

[ "$fail" = 0 ] && echo "PASS: one matcher, pinned inert, parameters load-bearing" \
    || { echo "FAIL: reconcile matcher"; exit 1; }
