#!/bin/sh
# test_reconcile_matcher.sh — ONE matcher, two callers, and the parameters
# that separate them (14z-95, GitHub #43(a), maintainer-ruled 2026-08-18).
#
# tools/reconcile_batch.py carried a COPY of tools/find_equiv.py's core, and
# the copy had drifted three ways: no relaxed-anchor fallback, a 64-hit cap
# applied BEFORE the score sort (so it keeps the first 64 by ADDRESS, not the
# best 64), and `return []` where find_equiv exits on an unusable window. The
# human-facing tool and the machine one therefore gave DIFFERENT ANSWERS for
# the same input, and 357 committed rows were generated by the drifted one.
#
# THE SPLIT THIS GATE POLICES. The maintainer split #43 on the line between
# what moves bytes and what does not:
#   (a) the refactor, pinned to the batch tool's then-measured parameters
#       (HIT_CAP=64, ALLOW_FALLBACK=False) — provably inert, landed 14z-95.
#   (b) flipping the fallback ON — re-resolves the three ruled rows and
#       moves built bytes. LANDED at the 14z-99 RE-FREEZE WINDOW
#       (maintainer "go", 2026-08-20). The tool now pins (64, True).
# Section 2 STILL asserts the (a) inertness — cmp_matchers pins the rb side
# at the HISTORICAL (64, False) for that comparison, so the proof stays
# reproducible after the flip. Section 3 asserts the parameters are
# load-bearing (the free comparison also runs from the historical pin, so
# its delta stays the measured constant).
#
# WHY THE OBVIOUS CONTROL WOULD PROVE NOTHING. reconcile_batch KEEPS existing
# rows ("existing rows win"), so re-running it against the committed manifest
# reproduces all 328 rows no matter which matcher is installed. A green
# re-emit is not evidence. The comparison has to be at the MATCHER, against
# the pre-refactor copy reconstructed from git.
#
# ROMDIR + git history. ~4 min (two decrypts + 3280 masked searches).
#
# HANDOFF's review-triage table note, moved into this header 14z-123 (verbatim; the
# documentation pass ruled a gate's WHY lives in the gate):
#   (review-triage, #43(a)) ONE matcher, two callers. `reconcile_batch`'s
#   drifted copy of `find_equiv`'s core is deleted; the three drifts survive
#   as parameters pinned to the batch tool's MEASURED values. Section 2 proves
#   the refactor inert against the pre-refactor copy reconstructed from git
#   (1640/1640 probes), with a must-fire control; section 3 proves the
#   parameters load-bearing (183/1640 change when freed), so #43(b) is a real
#   change and section 2 is not vacuous. **Not portable.**
set -eu
REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"
ROMDIR="${ROMDIR:?set ROMDIR}"
# 14z-132: ABSOLUTE. Gates `cd` into work dirs and then compose paths that
# still contain $ROMDIR (e.g. MAME_ROMPATH="...;$ROMDIR"); a RELATIVE value —
# which is how the runners invoke everything (ROMDIR=../ROMS) — then resolves
# against the WORK dir and silently finds no reference members. Kept as a
# VARIABLE (forks set their own); only made absolute, and only if it exists,
# so a gate that means to SKIP on a missing ROMDIR still does.
if [ -d "$ROMDIR" ]; then ROMDIR="$(cd "$ROMDIR" && pwd)"; fi
BASE="${RECONCILE_BASE_REV:-}"

W="$(mktemp -d)"; trap 'rm -rf "$W"' EXIT
fail=0
ok()  { echo "  ok: $1"; }
bad() { echo "FAIL: $1"; fail=1; }

echo "== 1: there is ONE implementation"
if grep -q "^def masked_search" tools/find_equiv.py; then
    ok "find_equiv.py owns masked_search"
else
    bad "find_equiv.py no longer defines masked_search"
fi
if grep -q "^def masked_search" tools/reconcile_batch.py; then
    bad "reconcile_batch.py has re-grown its own masked_search — that is the copy #43 deleted"
else
    ok "reconcile_batch.py defines no matcher of its own"
fi
grep -q "^import find_equiv" tools/reconcile_batch.py \
    && ok "reconcile_batch imports the canonical matcher" \
    || bad "reconcile_batch does not import find_equiv"
# the algorithm must not be pasted back in under another name
for marker in "dst_img.find(anchor" "mask.count(1)"; do
    if grep -q "$marker" tools/reconcile_batch.py; then
        bad "reconcile_batch contains matcher internals ('$marker') — a renamed copy is still a copy"
    fi
done
ok "no matcher internals in the batch tool"

echo "== 2: pinned parameters are INERT vs the pre-refactor copy"
# Reconstruct the drifted copy from the last commit that still had it. The
# revision is DERIVED, not pinned to a hash, so this keeps working as history
# grows; RECONCILE_BASE_REV overrides it.
# THE LOOKUP MUST TOLERATE ITS OWN COMMIT (14z-95). The first version took
# `git log -S ... | head -1` and used that commit's blob. `-S` reports the
# commit where the string COUNT CHANGED — which, once the refactor landed, is
# the commit that DELETED the function, whose blob no longer contains it. So
# the gate passed while the removal was uncommitted and SKIPPED itself the
# moment it was committed: a gate that disarms on the change it exists to
# police. Caught by run_all_static counting SKIP separately (GitHub #29) —
# had SKIP been folded into PASS, this would have read green.
# Fix: walk the candidates AND their parents, take the first blob that really
# carries the function.
if [ -z "$BASE" ]; then
    for _c in $(git log --format=%H -S 'def masked_search' -- tools/reconcile_batch.py); do
        for _rev in "$_c" "$_c^"; do
            if git show "$_rev:tools/reconcile_batch.py" 2>/dev/null \
                 | grep -q "^def masked_search"; then
                BASE="$_rev"; break
            fi
        done
        [ -n "$BASE" ] && break
    done
fi
if [ -z "$BASE" ] || ! git show "$BASE:tools/reconcile_batch.py" > "$W/rb_old.py" 2>/dev/null; then
    # Deliberately NOT the token a runner classifies as a skip: with no
    # reference implementation this gate's central assertion cannot run, and
    # that is a failure of the gate, not an absent optional input.
    bad "cannot reconstruct the pre-refactor copy from git — section 2 cannot run"
else
    git show "$BASE:tools/reconcile_batch.py" > "$W/rb_old.py"
    if grep -q "^def masked_search" "$W/rb_old.py"; then
        ok "reconstructed the drifted copy from $(echo "$BASE" | cut -c1-8)"
        if python3 tests/lib/cmp_matchers.py "$ROMDIR" "$W/rb_old.py"; then
            ok "pinned parameters reproduce the drifted copy on every probe"
        else
            bad "the refactor MOVED a result — this is a rule-6 finding."
            echo "     Do not adjust rows to make this green; attribute it."
        fi
        # MUST-FIRE: "1640 of 1640 identical" is equally consistent with a
        # comparison that cannot detect anything at all. Perturb the binding
        # and require the same comparison to go red.
        if python3 tests/lib/cmp_matchers.py "$ROMDIR" "$W/rb_old.py" --control; then
            ok "control: the comparison DOES detect a moved result"
        else
            bad "control did not fire — section 2's result proves nothing"
        fi
    else
        bad "$BASE carries no masked_search — the reference is wrong, so"
        echo "     section 2 would be comparing against nothing"
    fi
fi

echo "== 3: the parameters are LOAD-BEARING, not decoration"
# NB the helper exits 0 when the flags DO change results — "no difference" is
# the failure here, because a flag wired to nothing would make #43(b) a no-op
# and section 2's inertness result meaningless (everything is inert if nothing
# is connected).
if python3 tests/lib/cmp_matchers.py "$ROMDIR" --free; then
    ok "freeing the parameters changes results (so #43(b) is a real change)"
else
    bad "freeing hit_cap/allow_fallback changed NOTHING — the flags are dead,"
    echo "     which would make #43(b) a no-op and section 2 vacuous"
fi
python3 - <<'PYCHK' || bad "reconcile_batch is not pinned to its measured values"
import sys
sys.path.insert(0, "tools")
import reconcile_batch as rb
assert rb.HIT_CAP == 64, rb.HIT_CAP
assert rb.ALLOW_FALLBACK is True, rb.ALLOW_FALLBACK
print("  ok: reconcile_batch pinned at HIT_CAP=64, ALLOW_FALLBACK=True (#43(b), 14z-99)")
PYCHK

echo "== 4: an unusable window is DISTINGUISHABLE from no candidate (drift c)"
python3 - <<'PYCHK' || bad "the unusable-window signal is missing or wrong"
import sys
sys.path.insert(0, "tools")
import find_equiv, reconcile_batch
# Three `jsr $00028DD8` in a row: 18 bytes of which 12 are wildcarded
# operands, leaving 6 must-match — under the 8-byte floor. Sized
# deliberately: four of these would leave 8 hard bytes and NOT trip it, so
# a fixture that merely "looks operand-heavy" would test nothing.
src = bytes.fromhex("4eb900028dd8") * 3
dst = b"\x00" * 0x400
try:
    find_equiv.masked_search(src, dst, 0, 0x12)
except find_equiv.WindowUnusable as e:
    assert "operands" in str(e), e
    print("  ok: find_equiv RAISES WindowUnusable and names the reason")
else:
    sys.exit("find_equiv did not raise on an all-operand window")
# the batch tool converts it to [] on purpose (it retries other windows)
assert reconcile_batch._batch_search(src, dst, 0, 0x12) == []
print("  ok: the batch tool absorbs it as [] (it retries other window sizes)")
PYCHK

echo "== 5: the --allow-plausible claim matches reality"
# The docstring said "for experiment builds only" while build_merged.sh
# hardcodes it, so plausible rows ship in the artifact that gets played.
if grep -q "allow-plausible exists for experiment builds only" tools/reconcile_batch.py; then
    bad "the retracted '--allow-plausible is experiment-only' claim is back"
else
    ok "the experiment-only claim is not asserted"
fi
if grep -q -- "--allow-plausible" tools/build_merged.sh; then
    grep -q "PLAUSIBLE ROWS SHIP" tools/reconcile_batch.py \
        && ok "build_merged hardcodes it, and reconcile_batch says so" \
        || bad "build_merged hardcodes --allow-plausible and nothing records it"
else
    ok "build_merged no longer hardcodes --allow-plausible"
fi

echo "== 6: a TIED top cannot ship as a silent plausible (GitHub #107, 14z-101)"
# The 0x0448a6 row shipped as "plausible-0.94" for 96 sessions because the
# ladder's last-resort 0x20 window had FOUR candidates tied at 0.94 and the
# sort took the lowest address — the note recorded the score and hid the
# tie. Policy now: pick_window_hits refuses a tied top at ANY window (the
# ladder keeps trying richer ones); a target whose usable windows all tie
# lands OPEN with the tie NAMED in its note. NB the other plausible
# emitters (callsite-votes-{...}, farm-helper-xN) already disclose their
# ambiguity in the note and are not this class.
python3 - <<'PYCHK' || bad "the tie policy is missing or wrong"
import sys
sys.path.insert(0, "tools")
import reconcile_batch as rb

# unit outcomes of one window's decision
r = rb.pick_window_hits([(1.0, 0x100)], 0x40)
assert r == (0x100, "verified", "pattern-1.00-unique-w0x40"), r
r = rb.pick_window_hits([(0.94, 0x100), (0.80, 0x300)], 0x40)
assert r == (0x100, "plausible", "pattern-0.94-w0x40"), r
r = rb.pick_window_hits([(0.94, 0x100), (0.94, 0x200), (0.94, 0x300),
                         (0.94, 0x400)], 0x20)
assert r == ("tie", "TIE-4x0.94-w0x20"), r          # the literal #107 shape
r = rb.pick_window_hits([(1.0, 0x100), (1.0, 0x200)], 0x40)
assert r == ("tie", "TIE-2x1.00-w0x40"), r          # a tied 1.00 is still a tie
assert rb.pick_window_hits([(0.85, 0x100)], 0x40) is None
assert rb.pick_window_hits([], 0x40) is None
print("  ok: pick_window_hits — verified/plausible/tie/none all correct")

# the ladder: an early tie must not stop richer windows from deciding...
seq = {0x40: [(0.94, 0x100), (0.94, 0x200)], 0x30: [(0.97, 0x200)]}
r = rb.pattern_ladder(lambda w: seq.get(w, []), (0x40, 0x30, 0x20))
assert r == (0x200, "plausible", "pattern-0.97-w0x30"), r
print("  ok: pattern_ladder — a richer window may still discriminate a tie")
# ...and a target that ONLY ever ties lands OPEN with the tie named
seq = {0x20: [(0.94, 0x100), (0.94, 0x200)]}
r = rb.pattern_ladder(lambda w: seq.get(w, []), (0x40, 0x30, 0x20))
assert r == (None, "open", "TIE-2x0.94-w0x20"), r
print("  ok: pattern_ladder — an all-tie target is OPEN and says why")

# end-to-end through the REAL matcher: a code window duplicated verbatim at
# two dst sites must refuse; present once, it must resolve. The site is the
# #107 family prologue padded with nops so every ladder window is covered
# and the operand mask still leaves >=8 hard bytes.
site = (bytes.fromhex("102e0007323b00064efb1002000400147032")
        + b"\x4e\x71" * 0x40)
src = site + b"\x00" * 0x40
dst_tied = b"\x00" * 0x100 + site + b"\x00" * 0x100 + site + b"\x00" * 0x100
dst_one  = b"\x00" * 0x100 + site + b"\x00" * 0x200
ladder = (0x40, 0x30, 0x60, 0x80, 0x20)
def resolve(dst):
    return rb.pattern_ladder(
        lambda w: rb._batch_search(src, dst, 0, w), ladder)
cand, status, method = resolve(dst_tied)
assert status == "open" and method.startswith("TIE-2x"), (status, method)
print(f"  ok: end-to-end — a real two-site tie is refused ({method})")
cand, status, method = resolve(dst_one)                 # must-fire control
assert status == "verified" and cand == 0x100, (status, cand)
print(f"  ok: control — the single-site case still resolves ({status})")
PYCHK

[ "$fail" = 0 ] && echo "PASS: one matcher, pinned inert, parameters load-bearing" \
    || { echo "FAIL: reconcile matcher"; exit 1; }
