#!/bin/sh
# test_skill_guides.sh — the level-0 skills' GUIDE.md files are CURRENT
# against SKILL.md and the docs they quote (14z-134). ci_portable: no ROM, no
# build dir, no emulator, ~1 s.
#
# WHAT IT HOLDS. `mame-fbneo-instruments` [MFI] and `mister-jtframe-core`
# [MJC] are meant to be copied to other projects, so each ships the SMS shape:
# SKILL.md (the rules) + GUIDE.md (the human rendition — each rule followed by
# the INCIDENT that taught it). The guide is GENERATED by
# tools/gen_skill_guide.py from the documentation paragraph each rule is
# anchored to, so it cannot drift from the skill or the docs — this gate is
# the `--check` that says so, and it fails on a hand edit, a changed rule or a
# changed incident paragraph until the guide is regenerated in the same
# commit (the GENERATED-index discipline of CLAUDE.md §5).
#
# MUST-FIRE CONTROLS on a perturbed copy of the tree ([RH-9]: a negative
# control is wrong until it has failed on purpose): (a) a rule's text edited
# in SKILL.md; (b) an anchored incident paragraph edited in the doc; (c) the
# guide itself hand-edited. Each copy must FAIL `--check`.
set -u
REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"
fail=0
ok()  { printf '  ok    %s\n' "$1"; }
bad() { printf '  FAIL  %s\n' "$1"; fail=1; }

echo "== test_skill_guides: level-0 guides current =="
if python3 tools/gen_skill_guide.py --check >/tmp/skill_guides.$$.log 2>&1; then
    ok "gen_skill_guide.py --check PASS on the tree"; sed 's/^/        /' /tmp/skill_guides.$$.log
else
    bad "gen_skill_guide.py --check FAILS on the tree:"; sed 's/^/        /' /tmp/skill_guides.$$.log
fi
rm -f /tmp/skill_guides.$$.log

# the files the generator reads: the two skill dirs + every doc the checker
# lists for MFI/MJC (derived from the tool, never hard-coded here)
FILES="$(python3 - <<'EOF'
import sys; sys.path.insert(0, "tools")
import checkskills
seen = set()
for p in ("MFI", "MJC"):
    cfg = checkskills.SKILLS[p]
    d = cfg["path"].rsplit("/", 1)[0]
    for f in (cfg["path"], d + "/GUIDE.md", *cfg["docs"]):
        if f not in seen:
            seen.add(f); print(f)
EOF
)"
mkcopy() { for f in $FILES; do [ -f "$f" ] || continue; mkdir -p "$1/$(dirname "$f")"; cp "$f" "$1/$f"; done; mkdir -p "$1/tools"; cp tools/checkskills.py tools/gen_skill_guide.py "$1/tools/"; }
control() {  # control <label> <dir>
    if python3 tools/gen_skill_guide.py --root "$2" --check >"$2/log" 2>&1; then
        bad "$1: the perturbed copy PASSED — the check is not checking"
    elif grep -q "STALE" "$2/log"; then
        ok "$1: fires (STALE)"
    else
        bad "$1: failed for the wrong reason:"; sed 's/^/        /' "$2/log"
    fi
}
W="$(mktemp -d)"; trap 'rm -rf "$W"' EXIT INT TERM

mkcopy "$W/a"
sed -i.bak 's/^- \[MFI-9\] \*\*Watchpoint LENGTH/- [MFI-9] **Watchpoint WIDTH/' "$W/a/.claude/skills/mame-fbneo-instruments/SKILL.md"
grep -q 'Watchpoint WIDTH' "$W/a/.claude/skills/mame-fbneo-instruments/SKILL.md" || bad "control a: the rule was not edited"
control "a rule's text changed in SKILL.md" "$W/a"

mkcopy "$W/b"
python3 - "$W/b/docs/platform/gotchas.md" <<'EOF'
import sys, pathlib
p = pathlib.Path(sys.argv[1]); t = p.read_text()
i = t.index("**[MJC-2]**"); j = t.index("\n", i)
p.write_text(t[:j] + " (a word added to the incident)" + t[j:])
EOF
control "an incident paragraph changed in the doc" "$W/b"

mkcopy "$W/c"; printf '\nA line hand-added to the guide.\n' >> "$W/c/.claude/skills/mister-jtframe-core/GUIDE.md"
control "the guide hand-edited" "$W/c"

if [ "$fail" = 0 ]; then echo "PASS"; else echo "FAIL"; exit 1; fi
