#!/bin/sh
# PLAY.command — start VAMPIRE SAVED (merged-m19) on MAME.
#
# GENERATED by tools/package_release_platforms.py; do not edit by hand.
# Double-click it on macOS, or run `sh PLAY.command` from a terminal.
#
# It exists because getting this right by hand is the one step players were
# measured to fail: the set is `vsavjw`, which only the patched build knows, and it needs a rompath pointing at your built set — picking it from MAME's own list does not work.
set -eu
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"

say()  { printf '%s\n' "$*"; }
pause() { printf '\nPress Return to close this window.\n'; read _dummy 2>/dev/null || true; }
die()  { printf '\n!! %s\n' "$1" >&2; shift; for _l in "$@"; do printf '   %s\n' "$_l" >&2; done; pause; exit 1; }

say "VAMPIRE SAVED merged-m19 — MAME"
say ""

# ── 1. which prebuilt binary belongs to this machine ───────────────────────
case "$(uname -s)" in
Darwin) OS=macos ;;
Linux)  OS=linux ;;
MINGW*|MSYS*|CYGWIN*) OS=windows ;;
*) die "unsupported system: $(uname -s)" "This launcher knows macOS, Linux and MSYS2/Windows." ;;
esac
ARCH="$(uname -m)"
case "$ARCH" in arm64|aarch64) ARCH=arm64 ;; x86_64|amd64) ARCH=x86_64 ;; esac
OSARCH="$OS-$ARCH"
EXE="cps2"
[ "$OS" = windows ] && EXE="$EXE.exe"
BIN="$HERE/emulator/bin/$OSARCH/$EXE"

if [ ! -f "$BIN" ]; then
    _have="$(ls emulator/bin 2>/dev/null | tr '\n' ' ' || true)"
    die "no prebuilt mame for $OSARCH in this package." \
        "Present: ${_have:-none}" \
        "If you took the '-recipe' download, it ships the patch and EMULATOR.md" \
        "instead of a binary — build it once from those, then run it yourself." \
        "Otherwise no host has built $OSARCH yet."
fi
chmod +x "$BIN" 2>/dev/null || true

# ── 2. macOS quarantine (the binary is ad-hoc signed, NOT notarized) ───────
# A downloaded copy carries com.apple.quarantine and Gatekeeper refuses it on
# first launch. This is the one first-run problem on macOS and it is the
# player's own security state, so we ASK rather than silently clear it.
if [ "$OS" = macos ] && command -v xattr >/dev/null 2>&1; then
    if xattr -p com.apple.quarantine "$BIN" >/dev/null 2>&1; then
        say "macOS has quarantined this download, so it will refuse to launch."
        say "The binary is ad-hoc signed, not notarized — that is expected here."
        if [ -n "${PLAY_CLEAR_QUARANTINE:-}" ]; then
            _ans=y
        else
            printf 'Clear the quarantine flag on this folder now? [y/N] '
            read _ans 2>/dev/null || _ans=n
        fi
        case "$_ans" in
        y|Y|yes|YES)
            xattr -dr com.apple.quarantine "$HERE" || die "could not clear the quarantine flag." \
                "Run this yourself, then start again:" "  xattr -dr com.apple.quarantine '$HERE'"
            say "Cleared."
            ;;
        *)
            die "not cleared, so macOS will block the emulator." \
                "macOS shows: \"fbneo\" Not Opened — Apple could not verify ..." \
                "with only Done and Move to Bin. RIGHT-CLICK > OPEN DOES NOT GET PAST IT" \
                "on current macOS. What works is clearing the flag:" \
                "  xattr -dr com.apple.quarantine '$HERE'" \
                "then start this launcher again."
            ;;
        esac
        say ""
    fi
fi

# ── 3. is this actually the patched emulator? ──────────────────────────────
"$BIN" -listfull vsavjw >/dev/null 2>&1 || \
    die "that MAME does not know the vsavjw driver." \
        "A stock or Homebrew MAME never will. Use this package's binary," \
        "or build one with emulator/0002-cps2-wide-v1.patch per EMULATOR.md."

# ── 4. find the romset the applier built ──────────────────────────────────
# Looked for in the places a player plausibly puts it, nearest first.
ZIP=""
for _c in "$HERE/roms/vsavjw.zip" "$HERE/vsavjw.zip" "$HERE/rompath/vsavjw.zip"; do
    [ -f "$_c" ] && { ZIP="$_c"; break; }
done
if [ -z "$ZIP" ]; then
    die "vsavjw.zip not found." \
        "Build it from YOUR OWN dumps first — see README.md:" \
        "  python3 apply_release.py --romdir /path/to/your/dumps --out ./rompath" \
        "then put vsavjw.zip beside this launcher (or leave it in ./rompath/)."
fi
say "romset: $ZIP"
say "emulator: $BIN"
say ""

# PLAY_DRY_RUN is how the project's own gate drives this script without starting
# an emulator; it changes nothing else, and every check above has already run.
if [ -n "${PLAY_DRY_RUN:-}" ]; then
    say "WOULD RUN: $BIN vsavjw -rompath $(dirname "$ZIP") -skip_gameinfo"
    exit 0
fi
say "Starting. Tab opens MAME's own menu (controls, video); Esc exits."
say ""
exec "$BIN" vsavjw -rompath "$(dirname "$ZIP")" -skip_gameinfo "$@"
