@echo off
rem PLAY.bat - start VAMPIRE SAVED (merged-m22) with MAME on Windows.
rem
rem GENERATED by tools/package_release_platforms.py; do not edit by hand.
rem Double-click it in Explorer. Plain cmd: no PowerShell, no execution-policy prompt.
rem
rem It exists because getting this right by hand is the one step players were
rem measured to fail (GitHub #145): double-clicking cps2.exe finds no ROMs - the set is vsavjw, which only the patched build knows, and MAME needs -rompath pointing at your built set.
setlocal EnableExtensions
cd /d "%~dp0"
set "HERE=%CD%"
echo VAMPIRE SAVED merged-m22 - MAME on Windows
echo.

rem -- 1. the prebuilt binary for this machine
set "BINDIR=%HERE%\emulator\bin\windows-x86_64"
set "BIN=%BINDIR%\cps2.exe"
if exist "%BIN%" goto have_bin
echo !! no prebuilt mame for windows-x86_64 in this package.
echo    If you took the '-recipe' download, it ships the patch and EMULATOR.md
echo    instead of a binary - build it once from those, then run it yourself.
goto fail
:have_bin

rem -- 2. is this actually the patched emulator?
"%BIN%" -listfull vsavjw >nul 2>&1
if not errorlevel 1 goto profile_ok
echo !! that MAME does not know the vsavjw driver.
echo    A stock MAME never will. Use this package's binary,
echo    or build one with emulator\0002-cps2-wide-v1.patch per EMULATOR.md.
goto fail
:profile_ok

rem -- 3. find the romset the applier built, nearest first
set "ZIP="
for %%C in ("%HERE%\roms\vsavjw.zip" "%HERE%\vsavjw.zip" "%HERE%\rompath\vsavjw.zip") do if not defined ZIP if exist "%%~C" set "ZIP=%%~C"
if defined ZIP goto have_zip
echo !! vsavjw.zip not found.
echo    Build it from YOUR OWN dumps first - see README.md. The easy way:
echo    double-click apply_release.html, then save the vsavjw.zip it gives you
echo    into the "rompath" folder beside this launcher. Or, with Python installed:
echo      py apply_release.py --romdir C:\path\to\your\dumps --out rompath
echo    Then start this launcher again.
goto fail
:have_zip
for %%Z in ("%ZIP%") do set "ZIPDIR=%%~dpZ"
set "ZIPDIR=%ZIPDIR:~0,-1%"
echo romset: %ZIP%
echo emulator: %BIN%
echo.

cd /d "%HERE%"
rem PLAY_DRY_RUN is how the project's own gate drives this script without starting
rem an emulator; it changes nothing else, and every check above has already run.
if not defined PLAY_DRY_RUN goto launch
echo WOULD RUN: "%BIN%" vsavjw -rompath "%ZIPDIR%" -skip_gameinfo
exit /b 0
:launch
echo Starting. Tab opens MAME's own menu - controls, video. Esc exits.
echo.
"%BIN%" vsavjw -rompath "%ZIPDIR%" -skip_gameinfo %*
set "RC=%ERRORLEVEL%"
if "%RC%"=="0" exit /b 0
echo.
echo The emulator exited with code %RC%. Its own messages are above.
pause
exit /b %RC%

:fail
echo.
pause
exit /b 1
