#!/usr/bin/env python3
"""chain_census.py — the tenants' anim chain tables (from the generated
<tenant>_anim.md appendix pages, kept OUT of the tree under ../charpages/framedata/
and regenerated by tools/framedata_pages.sh) against the chains ANY naming rig
enters (tests/expected/move_naming_<t>.txt): per table, seqs / distinct chain
starts / entered / never entered; for a2 the never-entered seqs with node count,
attack records, sfx and how the chain ends. Alias seqs (same start) count once.
Written 14z-164 as a scratch census for GitHub #136; PROMOTED 14z-181 as the
reproduction of GitHub #174 (the never-entered a2 chains: 35 at 14z-164, 36 at the
14z-181 re-run once pyron_3's HP throw stopped whiffing into a2:0x03), whose index row had
cited only its build/ output (rule-checker run 2026-09-25-189).
usage: tools/framedata_pages.sh ; python3 tools/chain_census.py ../charpages/framedata"""
import re, sys
D = sys.argv[1]
for t in ('donovan', 'huitzil', 'pyron'):
    md = open(f'{D}/{t}_anim.md').read()
    starts = {}
    for m in re.finditer(r'^## table `(\w+)`.*?(?=^## table|\Z)', md, re.M | re.S):
        tab = m.group(1)
        for c in re.finditer(r"^### seq `(0x[0-9a-f]+)`(?: — \*\*(.*?)\*\*)? — start `(0x[0-9a-f]+)`, (\d+) nodes.*?\n(.*?)(?=^### |\Z)", m.group(0), re.M | re.S):
            body = c.group(5)
            rows = [r for r in body.split('\n') if r.startswith('| ') and not r.startswith('| #')]
            atk, sfx = set(), set()
            for r in rows:
                cc = [x.strip() for x in r.strip('|').split('|')]
                if len(cc) < 11: continue
                if cc[7]: atk.add(cc[7])
                if cc[9] not in ('', '0'): sfx.add(cc[9])
            end = c.group(0).split('\n')[0].split(' end ')[-1] if ' end ' in c.group(0).split('\n')[0] else '?'
            starts.setdefault(tab, {})[c.group(1)] = (c.group(3), c.group(2), int(c.group(4)), sorted(atk), sorted(sfx), end)
    entered = set()
    for l in open(f'tests/expected/move_naming_{t}.txt'):
        for c in l.rstrip('\n').split('\t')[2].replace('  FACING-LEFT', '').split(): entered.add(c)
    print(f"=== {t}: entered chains by any rig: {len(entered)}")
    for tab in ('a', 'a2', 'b', 'c'):
        if tab not in starts: continue
        allseq = starts[tab]; ent = {k for k in entered if k.startswith(tab + ':')}
        ent_starts = {allseq[k.split(':')[1]][0] for k in ent if k.split(':')[1] in allseq}
        distinct = {v[0] for v in allseq.values()}
        never = [(k, v) for k, v in allseq.items() if v[0] not in ent_starts]
        print(f"  table {tab}: {len(allseq)} seqs, {len(distinct)} distinct starts; entered {len(ent)} seqs / {len(ent_starts)} starts; never entered (distinct starts): {len(distinct - ent_starts)}; with attack records: {len({v[0] for k, v in never if v[3]})}")
        if tab == 'a2':
            for k, v in never:
                print(f"    a2:{k} nodes={v[2]} atk={v[3] if v[3] else '-'} sfx={v[4] if v[4] else '-'} end={v[5][:28]}")
