#!/usr/bin/env python3
"""charmap_md.py — render a tenant character-data map (charmap_gen.py JSON) as the
human page.

  python3 tools/charmap_md.py <map.json> <out.md>

Deterministic markdown: the gate (tests/test_charmap_current.sh) regenerates and
cmp's it. Sections: inputs; the diff summary; bank rows (vs2 | ours | source,
`!` on every difference); dispatch; regions (placement, sha1 both sides, diff
attribution counts, the capped unattributed sites); physics decoded; sfx
records; FSM state-node runs; sprite-list summary; overrides in effect; and
"What is NOT decoded", rendered from the map's `undecoded[]` — never
hand-written, so the page can only claim what the generator knows.
"""
import argparse
import json
from pathlib import Path


def h(s):
    return s.replace("|", "\\|")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("map", type=Path)
    ap.add_argument("out", type=Path)
    ap.add_argument("--anim", type=Path, help="write the anim-chain appendix page here")
    a = ap.parse_args()
    j = json.loads(a.map.read_text())
    S = j["structures"]
    o = []
    w = o.append
    w(f"# {j['tenant'].capitalize()} (char id {j['char']}) — character-data map, ours vs VS2")
    w("")
    w("GENERATED by `tools/charmap_gen.py` -> `tools/charmap_md.py` — do not edit by hand. "
      "Machine file: `docs/project/tables/chars/" + j["tenant"] + ".json`. Overrides: "
      "`build/manifest/charmap_" + j["tenant"] + ".toml` (compiled into the manifest by `tools/charmap_compile.py`). "
      "Gate: `tests/test_charmap_current.sh`.")
    w("")
    w(f"Sources: **vs2** = `{j['sources']['vs2']['set']}` extract (oracle `{j['sources']['vs2']['oracle']}`); "
      f"**ours** = the built image `{j['sources']['ours']['set']}`; **vh** = reserved (Vampire Hunter, no dump yet).")
    w("")
    w("## Inputs")
    w("")
    w("| input | SHA-1 |")
    w("|---|---|")
    for k, v in sorted(j["inputs"].items()):
        w(f"| `{k}` | `{v}` |")
    w("")
    w("## Diff summary")
    w("")
    w("| measure | value |")
    w("|---|---|")
    for k, v in sorted(j["diff_summary"].items()):
        w(f"| {k} | {v} |")
    w("")
    w("`ours_source` legend: `byte` = identical to vs2; `relocated` = a pointer field, checked against the placement "
      "(or the reconciliation twin for an engine address); `manifest:<mechanism>` = an existing manifest row explains it; "
      "`override:<id>` = a charmap override; `UNATTRIBUTED` = differs and nothing explains it (a finding).")
    w("")
    # ---- bank ----
    w("## The 32-row bank — this tenant's row in every table")
    w("")
    w("| table | kind | vsavj row | field | fmt | vs2 | ours | ! | ours_source |")
    w("|---|---|---|---|---|---|---|---|---|")
    for name, rec in S["bank"]["records"].items():
        loc = rec["loc"]
        for fn, fd in rec["fields"].items():
            flag = "**!**" if fd.get("diff") else ""
            extra = f" (expected placed `{fd['expected_placed']}`)" if fd.get("expected_placed") and fd.get("diff") else ""
            w(f"| `{name}` | {loc['kind']} | `{loc['vsavj_row']}` | {fn} | {fd['fmt']} | `{fd['vs2']}` | `{fd['ours']}` | {flag} | {h(str(fd.get('ours_source','')))}{extra} |")
    w("")
    # ---- dispatch ----
    w("## Dispatch rows (the per-character code pointers)")
    w("")
    w("| table | vs2 target | oracle | ours | expected placed | ! | ours_source |")
    w("|---|---|---|---|---|---|---|")
    for name, d in S["dispatch"].items():
        w(f"| `{name}` | `{d['vs2']}` | `{d['orc']}` | `{d['ours']}` | `{d['expected_placed']}` | {'**!**' if d['diff'] else ''} | {h(d['ours_source'])} |")
    w("")
    # ---- regions ----
    w("## Ported regions — placement and byte-diff attribution")
    w("")
    w("| region | kind | vs2 src | length | placed at | refs | variant sites | diff |")
    w("|---|---|---|---|---|---|---|---|")
    for name, r in S["regions"].items():
        d = r["diff"]
        if "counts" in d:
            c = d["counts"]
            txt = (f"total {c['total']}: relocated ok {c['relocated_ok']} / bad {c['relocated_bad']}, "
                   f"gfx_remap {c['gfx_remap']}, attributed {c['attributed']}, override {c['override']}, "
                   f"**unattributed {c['unattributed']}**")
        elif "bytes_differ" in d:
            txt = f"code: {d['bytes_differ']} bytes differ (out of scope — relocated code)"
        else:
            txt = d.get("note", "")
        w(f"| `{name}` | {r['kind']} | `{r['src']}` | {r['len']} | `{r['placed']}` | {r['refs']} | {r['variant_sites']} | {txt} |")
    w("")
    for name, r in S["regions"].items():
        d = r["diff"]
        if d.get("attributed_by"):
            w(f"`{name}` attributed by: " + ", ".join(f"`{k}` x{v}" for k, v in d["attributed_by"].items()))
            w("")
        sites = d.get("sites", [])
        if sites:
            w(f"<details><summary>`{name}`: first {len(sites)} unattributed / bad-relocation sites</summary>")
            w("")
            w("| off | kind | vs2 | ours | target |")
            w("|---|---|---|---|---|")
            for s_ in sites:
                w(f"| `{s_['off']}` | {s_['kind']} | `{s_['vs2']}` | `{s_['ours']}` | `{s_.get('target','')}` |")
            w("")
            w("</details>")
            w("")
    # ---- sfx ----
    if S["sfx"]:
        w("## Per-node sfx records (`[[sound_table]]`)")
        w("")
        for name, t in S["sfx"].items():
            L = t["loc"]
            w(f"`{name}`: vs2 array at `{L['src']}` (region `{L['region']}` + `{L['off']}`), {L['entries']} records, placed in `{L['placed_in']}`.")
            w("")
            w("| # | id | alt id | p4 | p5 | d3 | ours id | ours alt | ours_source |")
            w("|---|---|---|---|---|---|---|---|---|")
            for r in t["records"]:
                if "note" in r:
                    w(f"| {r['idx']} | | | | | | | | {r['note']} |")
                else:
                    w(f"| {r['idx']} | `{r['id']:#x}` | `{r['alt_id']:#x}` | {r['p4']} | {r['p5']} | `{r['d3']:#x}` | `{r['ours_id']:#x}` | `{r['ours_alt_id']:#x}` | {r['ours_source']} |")
            w("")
    # ---- fsm ----
    if S["fsm_nodes"]:
        w("## Object-script STATE node runs (0x20-byte nodes, `+0x10` counter, `+0x17` next state)")
        w("")
        for name, f in S["fsm_nodes"].items():
            w(f"`{name}`: {f['runs_vs2']} runs in vs2, {f['runs_ours']} in ours.")
            w("")
            w("| run @ offset | vs2 states | ours states | ! |")
            w("|---|---|---|---|")
            for r in f["runs"]:
                v = " ".join(f"{x:02x}" for x in r["vs2_states"]) if r["vs2_states"] else "—"
                u = " ".join(f"{x:02x}" for x in r["ours_states"]) if r["ours_states"] else "—"
                w(f"| `{r['off']}` | {v} | {u} | {'**!**' if r['diff'] else ''} |")
            w("")
    # ---- sprites ----
    if S["sprite_lists"]:
        sp = S["sprite_lists"]
        w("## Sprite lists in the anim region (`obj_records.walk` summary)")
        w("")
        w("| measure | vs2 | ours |")
        w("|---|---|---|")
        for k in ("records", "entries", "distinct_tiles"):
            w(f"| {k} | {sp[k]['vs2']} | {sp[k]['ours']} |")
        if sp.get("gfx_remap"):
            g = sp["gfx_remap"]
            w(f"\n`[gfx_remap]`: band `{g['band_lo']}`-`{g['band_hi']}`, delta `{g['delta']}`. {sp['note']}")
        w("")
    # ---- hitbox / attack records (phase 2) ----
    HB = S.get("hitbox") or {}
    if HB:
        sm = HB.get("_summary", {})
        w("## Hitboxes and attack records (phase 2)")
        w("")
        w(f"Base `{HB['base']}`, family table `{HB['family_table']}` ({HB['family_entries']} entries of {{vuln0, vuln1, vuln2, push}}), "
          f"tables {', '.join(f'{k} `{v}`' for k, v in HB['tables'].items())}; boxes {HB['box_counts']}. "
          f"{sm.get('attack_records', 0)} attack records ({sm.get('attack_differ', 0)} differ ours vs VS2, {sm.get('attack_unattributed', 0)} unattributed), "
          f"{sm.get('proj_records', 0)} projectile records ({sm.get('proj_differ', 0)} differ, {sm.get('proj_unattributed', 0)} unattributed). "
          f"Encoding: {HB['_encoding']}. Verified by `{HB['_verified_by']}`.")
        w("")
        w("| idx | addr | box (x, y, hw, hh) | real | white | hit id | class | +0x1C | ours differs | ours source |")
        w("|---|---|---|---|---|---|---|---|---|---|")
        for rec in HB["attack"]:
            f = rec["fields"]
            if f["box"] == [0, 0, 0, 0] and not f["real"] and not f["cls"] and not rec["ours_diff"]: continue
            w(f"| {rec['idx']:#x} | `{rec['addr']}` | {tuple(f['box'])} | {f['real']} | {f['white']} | {f['hit_id']} | {f['cls']:#04x} | {f['b1c']:#04x} | {' '.join(rec['ours_diff'])} | {rec['ours_source'] if rec['ours_diff'] else ''} |")
        if HB.get("proj"):
            w("")
            w("Projectile records (`hitbox_proj`):")
            w("")
            w("| idx | addr | box | real | white | hit id | class | +0x1C | ours differs | ours source |")
            w("|---|---|---|---|---|---|---|---|---|---|")
            for rec in HB["proj"]:
                f = rec["fields"]
                if f["box"] == [0, 0, 0, 0] and not f["real"] and not f["cls"] and not rec["ours_diff"]: continue
                w(f"| {rec['idx']:#x} | `{rec['addr']}` | {tuple(f['box'])} | {f['real']} | {f['white']} | {f['hit_id']} | {f['cls']:#04x} | {f['b1c']:#04x} | {' '.join(rec['ours_diff'])} | {rec['ours_source'] if rec['ours_diff'] else ''} |")
        w("")
    # ---- anim summary (+ appendix) ----
    A = S.get("anim") or {}
    if A:
        sm = A.get("_summary", {})
        w("## Animation node chains (phase 1) — summary")
        w("")
        w(f"{sm.get('nodes',0)} nodes across the five index tables; {sm.get('differ',0)} nodes differ from vs2 in a decoded field "
          f"({sm.get('attributed',0)} attributed). Verified by `{A.get('_verified_by','')}`. Per-chain detail: the appendix page `" + j["tenant"] + "_anim.md`.")
        w("")
        w("| table | vs2 table | ours table | entries | chains | nodes | loops | holds |")
        w("|---|---|---|---|---|---|---|---|")
        for tn in ("a", "a2", "b", "c", "proj"):
            T = A.get(tn)
            if not T: continue
            ch = T["chains"]
            w(f"| `{tn}` | `{T['table_vs2']}` | `{T['table_ours']}` | {T['entries']} | {len(ch)} | {sum(c['n'] for c in ch.values())} | "
              f"{sum(1 for c in ch.values() if c['end'].startswith('loop'))} | {sum(1 for c in ch.values() if c['end']=='hold')} |")
        w("")
        if a.anim:
            # MOVE NAMES (phase 1 naming step, 14z-120): build/manifest/moves_<tenant>.toml
            # rows carry table/seq measured by tools/name_moves.py; label each chain.
            names = {}
            mv = Path(__file__).resolve().parent.parent / "build" / "manifest" / f"moves_{j['tenant']}.toml"
            if mv.exists():
                import sys as _sys
                _sys.path.insert(0, str(Path(__file__).resolve().parent))
                import _minitoml
                for r in _minitoml.loads(mv.read_text()).get("move", []):
                    if r.get("table") and r.get("seq"):
                        inputs = [x.strip() for x in r["input"].split(",")]
                        seqs = [x.strip() for x in r["seq"].split(",")]
                        if len(seqs) == 3 and len(inputs) != 3:      # LP/MP/HP (or LK/MK/HK) of one motion
                            inputs = [st + inputs[0][-1] for st in ("L", "M", "H")]
                        for k, q in enumerate(seqs):
                            lab = r["name"] + (f" [{inputs[k]}]" if len(seqs) > 1 and k < len(inputs) else "")
                            names.setdefault((r["table"], int(q, 16)), []).append(lab)
            ao = []
            ao.append(f"# {j['tenant'].capitalize()} — animation node chains (appendix of the character-data map)")
            ao.append("")
            ao.append("GENERATED by `tools/charmap_md.py --anim` from the map JSON. One block per chain; one line per node: "
                      "`addr` (vs2) · `off` (region offset) · dur · flags · hb8 (the hitbox FAMILY: vuln/push ids) · hbA (hbA>>8 = the ATTACK record, shown in `atk rec`) · shadow seq · sfx idx · link · `!` if ours differs (with the attribution). Frame data per chain is derived from the attack nodes (phase 2).")
            ao.append("")
            for tn in ("a", "a2", "b", "c", "proj"):
                T = A.get(tn)
                if not T: continue
                ao.append(f"## table `{tn}` — {T['entries']} entries (vs2 `{T['table_vs2']}`, ours `{T['table_ours']}`)")
                ao.append("")
                named = sum(1 for seq in T["chains"] if (tn, int(seq, 16)) in names)
                if names:
                    ao.append(f"Named chains: {named} of {T['entries']} (from `build/manifest/moves_{j['tenant']}.toml`, measured by `tests/test_move_naming.sh`).")
                    ao.append("")
                for seq, c in T["chains"].items():
                    if not c["start"]:
                        ao.append(f"- seq `{seq}`: unused"); continue
                    lab = names.get((tn, int(seq, 16)))
                    ao.append(f"### seq `{seq}`" + (f" — **{' / '.join(lab)}**" if lab else "") + f" — start `{c['start']}`, {c['n']} nodes, {c['frames']} frames, end {c['end']}"
                              + ("" if c['ours_end'] == c['end'] else f" (ours: {c['ours_end']})"))
                    # phase 2: startup / active / recovery from the nodes' hbA words (hbA != 0 = an attack node, hbA>>8 = the record)
                    durs = [n["fields"]["dur"]["vs2"] for n in c["nodes"]]; atk = [n["fields"]["hbA"]["vs2"] >> 8 for n in c["nodes"]]
                    if any(atk):
                        first = next(i for i, a in enumerate(atk) if a); last = max(i for i, a in enumerate(atk) if a)
                        recs = sorted({a for a in atk if a})
                        ao.append("")
                        ao.append(f"Frame data (derived): startup {sum(durs[:first])} · active {sum(durs[first:last + 1])} (nodes {first}-{last}, attack record{'s' if len(recs) > 1 else ''} {', '.join(f'{x:#x}' for x in recs)}) · recovery {sum(durs[last + 1:])}"
                                  + (" — the chain loops/holds, so the tail is the data's, not the move's" if not c["end"] == "hold" else ""))
                    ao.append("")
                    ao.append("| # | addr | off | dur | flags | hb8 | hbA | atk rec | shadow | sfx | link | ! |")
                    ao.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
                    for k, n in enumerate(c["nodes"]):
                        f = n["fields"]
                        flag = ("**!** " + n["ours_source"] + " (" + ",".join(n["diff"]) + ")") if n["diff"] else ""
                        ar = f"**{f['hbA']['vs2'] >> 8:#x}**" if f['hbA']['vs2'] else ""
                        ao.append(f"| {k} | `{n['addr']}` | `{n['off']}` | {f['dur']['vs2']} | {f['flags']['vs2']:#04x} | {f['hb8']['vs2']} | {f['hbA']['vs2']} | {ar} | {f['shadow']['vs2']} | {f['sfx']['vs2']} | {f.get('link',{}).get('vs2','')} | {flag} |")
                    ao.append("")
            a.anim.write_text("\n".join(ao))
            print(f"wrote {a.anim} ({len(ao)} lines)")
    # ---- overrides ----
    w("## Overrides in effect (`charmap_" + j["tenant"] + ".toml`)")
    w("")
    if j["overrides"]:
        w("| id | region | off | vs2 | ours | stage | note |")
        w("|---|---|---|---|---|---|---|")
        for ov in j["overrides"]:
            w(f"| `{ov['id']}` | `{ov['region']}` | `{ov['off']:#x}` | `{ov['expect']}` | `{ov['value']}` | {ov['stage']} | {h(ov['note'])} |")
    else:
        w("(none)")
    w("")
    # ---- undecoded ----
    w("## What is NOT decoded (the worklist — shrinks only by a measurement with a gate)")
    w("")
    w("| structure | what | evidence today |")
    w("|---|---|---|")
    for u in j["undecoded"]:
        w(f"| {u['structure']} | {h(u['what'])} | {h(u['evidence'])} |")
    w("")
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text("\n".join(o))
    print(f"wrote {a.out} ({len(o)} lines)")


if __name__ == "__main__":
    main()
