#!/usr/bin/env python3
"""charmap_md.py — render a tenant character-data map (charmap_gen.py JSON) as the
human page.

  python3 tools/charmap_md.py <map.json> <out.md>

Deterministic markdown: the gate (tests/test_charmap_current.sh) regenerates and
cmp's it. Sections: inputs; the diff summary; bank rows (vs2 | ours | source,
`!` on every difference); dispatch; regions (placement, sha1 both sides, diff
attribution counts, the capped unattributed sites); physics decoded; sfx
records; FSM state-node runs; sprite-list summary; overrides in effect; and
"What is NOT decoded", rendered from the map's `undecoded[]` — never
hand-written, so the page can only claim what the generator knows.
"""
import argparse
import json
from pathlib import Path


def h(s):
    return s.replace("|", "\\|")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("map", type=Path)
    ap.add_argument("out", type=Path)
    ap.add_argument("--anim", type=Path, help="write the anim-chain appendix page here")
    a = ap.parse_args()
    j = json.loads(a.map.read_text())
    S = j["structures"]
    o = []
    w = o.append
    w(f"# {j['tenant'].capitalize()} (char id {j['char']}) — character-data map, ours vs VS2")
    w("")
    w("GENERATED by `tools/charmap_gen.py` -> `tools/charmap_md.py` — do not edit by hand. "
      "Machine file: `docs/project/tables/chars/" + j["tenant"] + ".json`. Overrides: "
      "`build/manifest/charmap_" + j["tenant"] + ".toml` (compiled into the manifest by `tools/charmap_compile.py`). "
      "Gate: `tests/test_charmap_current.sh`.")
    w("")
    w(f"Sources: **vs2** = `{j['sources']['vs2']['set']}` extract (oracle `{j['sources']['vs2']['oracle']}`); "
      f"**ours** = the built image `{j['sources']['ours']['set']}`; **vh** = reserved (Vampire Hunter, no dump yet).")
    w("")
    w("## Inputs")
    w("")
    w("| input | SHA-1 |")
    w("|---|---|")
    for k, v in sorted(j["inputs"].items()):
        w(f"| `{k}` | `{v}` |")
    w("")
    w("## Diff summary")
    w("")
    w("| measure | value |")
    w("|---|---|")
    for k, v in sorted(j["diff_summary"].items()):
        w(f"| {k} | {v} |")
    w("")
    w("`ours_source` legend: `byte` = identical to vs2; `relocated` = a pointer field, checked against the placement "
      "(or the reconciliation twin for an engine address); `manifest:<mechanism>` = an existing manifest row explains it; "
      "`override:<id>` = a charmap override; `UNATTRIBUTED` = differs and nothing explains it (a finding).")
    w("")
    # ---- bank ----
    w("## The 32-row bank — this tenant's row in every table")
    w("")
    w("| table | kind | vsavj row | field | fmt | vs2 | ours | ! | ours_source |")
    w("|---|---|---|---|---|---|---|---|---|")
    for name, rec in S["bank"]["records"].items():
        loc = rec["loc"]
        for fn, fd in rec["fields"].items():
            flag = "**!**" if fd.get("diff") else ""
            extra = f" (expected placed `{fd['expected_placed']}`)" if fd.get("expected_placed") and fd.get("diff") else ""
            w(f"| `{name}` | {loc['kind']} | `{loc['vsavj_row']}` | {fn} | {fd['fmt']} | `{fd['vs2']}` | `{fd['ours']}` | {flag} | {h(str(fd.get('ours_source','')))}{extra} |")
    w("")
    # ---- dispatch ----
    w("## Dispatch rows (the per-character code pointers)")
    w("")
    w("| table | vs2 target | oracle | ours | expected placed | ! | ours_source |")
    w("|---|---|---|---|---|---|---|")
    for name, d in S["dispatch"].items():
        w(f"| `{name}` | `{d['vs2']}` | `{d['orc']}` | `{d['ours']}` | `{d['expected_placed']}` | {'**!**' if d['diff'] else ''} | {h(d['ours_source'])} |")
    w("")
    # ---- regions ----
    w("## Ported regions — placement and byte-diff attribution")
    w("")
    w("| region | kind | vs2 src | length | placed at | refs | variant sites | diff |")
    w("|---|---|---|---|---|---|---|---|")
    for name, r in S["regions"].items():
        d = r["diff"]
        if "counts" in d:
            c = d["counts"]
            txt = (f"total {c['total']}: relocated ok {c['relocated_ok']} / bad {c['relocated_bad']}, "
                   f"gfx_remap {c['gfx_remap']}, attributed {c['attributed']}, override {c['override']}, "
                   f"**unattributed {c['unattributed']}**")
        elif "bytes_differ" in d:
            txt = f"code: {d['bytes_differ']} bytes differ (out of scope — relocated code)"
        else:
            txt = d.get("note", "")
        w(f"| `{name}` | {r['kind']} | `{r['src']}` | {r['len']} | `{r['placed']}` | {r['refs']} | {r['variant_sites']} | {txt} |")
    w("")
    for name, r in S["regions"].items():
        d = r["diff"]
        if d.get("attributed_by"):
            w(f"`{name}` attributed by: " + ", ".join(f"`{k}` x{v}" for k, v in d["attributed_by"].items()))
            w("")
        sites = d.get("sites", [])
        if sites:
            w(f"<details><summary>`{name}`: first {len(sites)} unattributed / bad-relocation sites</summary>")
            w("")
            w("| off | kind | vs2 | ours | target |")
            w("|---|---|---|---|---|")
            for s_ in sites:
                w(f"| `{s_['off']}` | {s_['kind']} | `{s_['vs2']}` | `{s_['ours']}` | `{s_.get('target','')}` |")
            w("")
            w("</details>")
            w("")
    # ---- sfx ----
    if S["sfx"]:
        w("## Per-node sfx records (`[[sound_table]]`)")
        w("")
        for name, t in S["sfx"].items():
            L = t["loc"]
            w(f"`{name}`: vs2 array at `{L['src']}` (region `{L['region']}` + `{L['off']}`), {L['entries']} records, placed in `{L['placed_in']}`.")
            w("")
            w("| # | id | alt id | p4 | p5 | d3 | ours id | ours alt | ours_source |")
            w("|---|---|---|---|---|---|---|---|---|")
            for r in t["records"]:
                if "note" in r:
                    w(f"| {r['idx']} | | | | | | | | {r['note']} |")
                else:
                    w(f"| {r['idx']} | `{r['id']:#x}` | `{r['alt_id']:#x}` | {r['p4']} | {r['p5']} | `{r['d3']:#x}` | `{r['ours_id']:#x}` | `{r['ours_alt_id']:#x}` | {r['ours_source']} |")
            w("")
    # ---- fsm ----
    if S["fsm_nodes"]:
        w("## Object-script STATE node runs (0x20-byte nodes, `+0x10` counter, `+0x17` next state)")
        w("")
        for name, f in S["fsm_nodes"].items():
            w(f"`{name}`: {f['runs_vs2']} runs in vs2, {f['runs_ours']} in ours.")
            w("")
            w("| run @ offset | vs2 states | ours states | ! |")
            w("|---|---|---|---|")
            for r in f["runs"]:
                v = " ".join(f"{x:02x}" for x in r["vs2_states"]) if r["vs2_states"] else "—"
                u = " ".join(f"{x:02x}" for x in r["ours_states"]) if r["ours_states"] else "—"
                w(f"| `{r['off']}` | {v} | {u} | {'**!**' if r['diff'] else ''} |")
            w("")
    # ---- sprites ----
    if S["sprite_lists"]:
        sp = S["sprite_lists"]
        w("## Sprite lists in the anim region (`obj_records.walk` summary)")
        w("")
        w("| measure | vs2 | ours |")
        w("|---|---|---|")
        for k in ("records", "entries", "distinct_tiles"):
            w(f"| {k} | {sp[k]['vs2']} | {sp[k]['ours']} |")
        if sp.get("gfx_remap"):
            g = sp["gfx_remap"]
            w(f"\n`[gfx_remap]`: band `{g['band_lo']}`-`{g['band_hi']}`, delta `{g['delta']}`. {sp['note']}")
        w("")
    # ---- anim summary (+ appendix) ----
    A = S.get("anim") or {}
    if A:
        sm = A.get("_summary", {})
        w("## Animation node chains (phase 1) — summary")
        w("")
        w(f"{sm.get('nodes',0)} nodes across the five index tables; {sm.get('differ',0)} nodes differ from vs2 in a decoded field "
          f"({sm.get('attributed',0)} attributed). Verified by `{A.get('_verified_by','')}`. Per-chain detail: the appendix page `" + j["tenant"] + "_anim.md`.")
        w("")
        w("| table | vs2 table | ours table | entries | chains | nodes | loops | holds |")
        w("|---|---|---|---|---|---|---|---|")
        for tn in ("a", "a2", "b", "c", "proj"):
            T = A.get(tn)
            if not T: continue
            ch = T["chains"]
            w(f"| `{tn}` | `{T['table_vs2']}` | `{T['table_ours']}` | {T['entries']} | {len(ch)} | {sum(c['n'] for c in ch.values())} | "
              f"{sum(1 for c in ch.values() if c['end'].startswith('loop'))} | {sum(1 for c in ch.values() if c['end']=='hold')} |")
        w("")
        if a.anim:
            ao = []
            ao.append(f"# {j['tenant'].capitalize()} — animation node chains (appendix of the character-data map)")
            ao.append("")
            ao.append("GENERATED by `tools/charmap_md.py --anim` from the map JSON. One block per chain; one line per node: "
                      "`addr` (vs2) · `off` (region offset) · dur · flags · hb8/hbA (hitbox-family words) · shadow seq · sfx idx · link · `!` if ours differs (with the attribution).")
            ao.append("")
            for tn in ("a", "a2", "b", "c", "proj"):
                T = A.get(tn)
                if not T: continue
                ao.append(f"## table `{tn}` — {T['entries']} entries (vs2 `{T['table_vs2']}`, ours `{T['table_ours']}`)")
                ao.append("")
                for seq, c in T["chains"].items():
                    if not c["start"]:
                        ao.append(f"- seq `{seq}`: unused"); continue
                    ao.append(f"### seq `{seq}` — start `{c['start']}`, {c['n']} nodes, {c['frames']} frames, end {c['end']}"
                              + ("" if c['ours_end'] == c['end'] else f" (ours: {c['ours_end']})"))
                    ao.append("")
                    ao.append("| # | addr | off | dur | flags | hb8 | hbA | shadow | sfx | link | ! |")
                    ao.append("|---|---|---|---|---|---|---|---|---|---|---|")
                    for k, n in enumerate(c["nodes"]):
                        f = n["fields"]
                        flag = ("**!** " + n["ours_source"] + " (" + ",".join(n["diff"]) + ")") if n["diff"] else ""
                        ao.append(f"| {k} | `{n['addr']}` | `{n['off']}` | {f['dur']['vs2']} | {f['flags']['vs2']:#04x} | {f['hb8']['vs2']} | {f['hbA']['vs2']} | {f['shadow']['vs2']} | {f['sfx']['vs2']} | {f.get('link',{}).get('vs2','')} | {flag} |")
                    ao.append("")
            a.anim.write_text("\n".join(ao))
            print(f"wrote {a.anim} ({len(ao)} lines)")
    # ---- overrides ----
    w("## Overrides in effect (`charmap_" + j["tenant"] + ".toml`)")
    w("")
    if j["overrides"]:
        w("| id | region | off | vs2 | ours | stage | note |")
        w("|---|---|---|---|---|---|---|")
        for ov in j["overrides"]:
            w(f"| `{ov['id']}` | `{ov['region']}` | `{ov['off']:#x}` | `{ov['expect']}` | `{ov['value']}` | {ov['stage']} | {h(ov['note'])} |")
    else:
        w("(none)")
    w("")
    # ---- undecoded ----
    w("## What is NOT decoded (the worklist — shrinks only by a measurement with a gate)")
    w("")
    w("| structure | what | evidence today |")
    w("|---|---|---|")
    for u in j["undecoded"]:
        w(f"| {u['structure']} | {h(u['what'])} | {h(u['evidence'])} |")
    w("")
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text("\n".join(o))
    print(f"wrote {a.out} ({len(o)} lines)")


if __name__ == "__main__":
    main()
