#!/usr/bin/env python3
"""charmap_compile.py — turn the hand-written character-data OVERRIDES into the
build's own [[region_fix]] rows, inside a marked block of the tenant manifest.

  python3 tools/charmap_compile.py <map.json> <overrides.toml> <tenant.toml> [--check]

THE CHANNEL (maintainer-ruled 2026-08-29: "edit the machine file; the build
consumes it"). The generated map (docs/project/tables/chars/<tenant>.json) is
never edited by hand. A data change is one row in the small, hand-written
build/manifest/charmap_<tenant>.toml:

    [[override]]
    id = "deity_class_0"
    path = "region/hitbox/0x11a9"      # phase 0: region/<name>/<hex offset>; later phases add structured paths
    expect = "4e"                       # the vs2 byte(s) — the old-guard, verified against the extract
    value = "06"                        # ours — SAME length (tools/audit_hex_lengths.py law)
    stage = 6
    note = "sworded deity hit 1/7: type 0x4E -> 0x06"

This tool rewrites ONLY the block between
    # BEGIN charmap (generated by tools/charmap_compile.py — do not edit by hand)
    # END charmap
in the tenant manifest with one [[region_fix]] row per override (region, off,
old_hex, new_hex, stage, note = "charmap:<id> <note>"). gen_donovan_patch.py
consumes those rows exactly as it consumes hand-written ones (old-verified
against the extracted source bytes) — NO change to the generator. Rows outside
the block are untouched and keep working; the map reports them as
`manifest:` sources. `--check` compiles to memory and exits 1 if the block on
disk differs (the gate's mode).

Refuses: an override whose `expect` does not match the vs2 bytes in the map's
extract (the map generator already verified this — the compiler re-verifies
against the extract dir named in the map), an expect/value length mismatch, a
duplicate id, a path outside the phase-0 grammar.
"""
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _minitoml import loads as toml_loads  # noqa: E402

BEGIN = "# BEGIN charmap (generated by tools/charmap_compile.py — do not edit by hand)"
END = "# END charmap"


def rows(doc, key):
    v = doc.get(key, [])
    return v if isinstance(v, list) else [v]


def compile_rows(mapj, ovdoc, extract_dir):
    out = []
    seen = set()
    for o in rows(ovdoc, "override"):
        oid = str(o["id"])
        if oid in seen:
            raise SystemExit(f"override {oid}: duplicate id")
        seen.add(oid)
        parts = str(o["path"]).split("/")
        if len(parts) != 3 or parts[0] != "region":
            raise SystemExit(f"override {oid}: path must be region/<name>/<hexoff> in phase 0 (got {o['path']})")
        region, off = parts[1], int(parts[2], 16)
        exp = bytes.fromhex(str(o["expect"]))
        val = bytes.fromhex(str(o["value"]))
        if len(exp) != len(val) or not exp:
            raise SystemExit(f"override {oid}: expect/value must be the same non-zero length")
        if region not in mapj["structures"]["regions"]:
            raise SystemExit(f"override {oid}: region {region!r} is not in the map")
        blob = (Path(extract_dir) / f"region_{region}.bin").read_bytes()
        if blob[off: off + len(exp)] != exp:
            raise SystemExit(f"override {oid}: vs2 bytes at {region}+{off:#x} are {blob[off:off+len(exp)].hex()}, expect {exp.hex()}")
        note = str(o.get("note", "")).replace('"', "'")
        out.append("\n".join([
            "[[region_fix]]",
            f"stage = {int(o.get('stage', 6))}",
            f'region = "{region}"',
            f"off = {off:#x}",
            f'old_hex = "{exp.hex()}"',
            f'new_hex = "{val.hex()}"',
            f'note = "charmap:{oid} {note}"',
        ]))
    return out


def splice(text, block_lines):
    lines = text.split("\n")
    try:
        b = lines.index(BEGIN)
        e = lines.index(END)
    except ValueError:
        raise SystemExit("the tenant manifest has no charmap block — add the two marker lines once by hand")
    if e < b:
        raise SystemExit("charmap markers out of order")
    body = []
    for r in block_lines:
        body += r.split("\n") + [""]
    if not block_lines:
        body = ["# (no overrides in charmap_<tenant>.toml)", ""]
    return "\n".join(lines[: b + 1] + [""] + body + lines[e:])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("map", type=Path)
    ap.add_argument("overrides", type=Path)
    ap.add_argument("manifest", type=Path)
    ap.add_argument("--check", action="store_true", help="exit 1 if the manifest block differs from a fresh compile")
    a = ap.parse_args()
    mapj = json.loads(a.map.read_text())
    extract_dir = Path(mapj["sources"]["ours"]["set"]) / "extract"
    if not extract_dir.is_absolute():
        extract_dir = Path(__file__).resolve().parent.parent / extract_dir
    ovdoc = toml_loads(a.overrides.read_text()) if a.overrides.is_file() else {}
    block = compile_rows(mapj, ovdoc, extract_dir)
    text = a.manifest.read_text()
    new = splice(text, block)
    if a.check:
        if new != text:
            print(f"FAIL: {a.manifest} charmap block differs from a fresh compile of {a.overrides} ({len(block)} rows)")
            sys.exit(1)
        print(f"ok: {a.manifest} charmap block is current ({len(block)} override rows)")
        return
    if new != text:
        a.manifest.write_text(new)
        print(f"wrote {a.manifest}: charmap block = {len(block)} [[region_fix]] rows")
    else:
        print(f"unchanged {a.manifest} ({len(block)} rows)")


if __name__ == "__main__":
    main()
