#!/usr/bin/env python3
"""gen_gate_coverage.py — docs/project/gate_coverage.md, WHAT EACH GATE TESTS, is GENERATED.

  python3 tools/gen_gate_coverage.py            # rewrite docs/project/gate_coverage.md
  python3 tools/gen_gate_coverage.py --check    # regenerate, cmp, diff on drift
  python3 tools/gen_gate_coverage.py --root DIR # a copy of the tree (controls)

WHY THIS EXISTS (14z-180, GitHub #171 slice Q0 — the maintainer's ruling: "I want for
each test a human-readable description of the test (at least what it tests, how it
tests and what is the expected result)", and on the page: "I want the doc I read to
be generated from the headers themselves, to avoid it rotting in the future"). Every
gate's `# WHAT:` / `# HOW:` / `# EXPECTS:` header fields, read by
tools/gate_descriptions.py (the ONE reader), rendered for READING by family: one entry
per described gate, the not-yet-described listed at the family's end, so the
functional coverage and the retrofit's remainder are on one page.

WHY A SEPARATE GENERATOR and not a second table in gate_index.md: the generic
harness (bbh) carries a lifted COPY of tools/gen_gate_index.py and its fidelity gate
F9 requires the two to render the index byte-identically (tests/test_bbh_fidelity.sh).
A description table added to the index broke F9 at 14z-180; the index stays what the
harness renders, and this page is the tree's own. The rows (family, kind, tier) come
from gen_gate_index.collect(), so the two pages cannot disagree about a gate.
ROM-free, ~0.3 s. Gate: tests/test_gate_coverage_current.sh.
"""
import argparse
import difflib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_gate_index          # the rows: family, kind, tier — the one classifier of the tree's gates
import gate_descriptions       # the one reader of the three fields

REPO = Path(__file__).resolve().parent.parent
OUT = "docs/project/gate_coverage.md"

PREAMBLE = """\
# What each gate tests (GENERATED)

<!-- generated by tools/gen_gate_coverage.py — do not edit; regenerate -->

**STATUS: GENERATED (14z-180, GitHub #171 slice Q0).** The human-readable description of
every gate under `tests/`, read from each script's own `# WHAT:` / `# HOW:` / `# EXPECTS:`
header fields by `tools/gate_descriptions.py` and rendered here by family — the
functional-coverage view the maintainer reviews. The header is the source: a description
that reads wrong is corrected in the gate, never here. Gates not yet describing themselves
are listed at the end of their family; `tests/test_gate_descriptions.sh` freezes that
remainder so it only shrinks. Regenerate with `python3 tools/gen_gate_coverage.py`;
`tests/test_gate_coverage_current.sh` fails when this page is stale. The grammar is
`docs/project/gate_header_contract.md`; the technical index (tier, needs, the header's
first sentence) is `gate_index.md`.
"""


def safe(text):
    """Description text as the site's markdown subset must see it: a token carrying a
    bare `*` outside a code span (`tests/*.sh`) is wrapped in backticks, or the subset's
    italic rule pairs two of them into an <em>; a token shaped like a tag (`<header>`) is
    wrapped too, or the subset rejects it as raw HTML (test_docs_site went red on each,
    14z-180). Existing code spans are left alone."""
    parts = re.split(r"(`[^`]*`)", text)
    for i in range(0, len(parts), 2):
        parts[i] = " ".join(
            f"`{t}`" if ("*" in t or re.search(r"</?[A-Za-z][A-Za-z0-9-]*>", t)) else t
            for t in parts[i].split(" "))
    return "".join(parts)


def collect(root):
    rows, problems = gen_gate_index.collect(root)
    for r in rows:
        text = (root / r["gate"]).read_text(encoding="utf-8", errors="replace")
        desc, desc_problems = gate_descriptions.parse(text)
        r["desc"] = desc if not desc_problems else None
    return rows, problems


def render(rows):
    out = [PREAMBLE]
    n = len(rows)
    nd = sum(1 for r in rows if r["desc"])
    out.append(f"**{nd} of {n} gates described.**\n")
    out.append("| family | described | of | what the family is |\n|---|---|---|---|")
    for f, desc in gen_gate_index.FAMILIES:
        fr = [r for r in rows if r["family"] == f]
        out.append(f"| [{f}](#{f}) | {sum(1 for r in fr if r['desc'])} | {len(fr)} | {desc} |")
    out.append("")
    for f, desc in gen_gate_index.FAMILIES:
        fam_rows = [r for r in rows if r["family"] == f]
        if not fam_rows:
            continue
        described = sorted([r for r in fam_rows if r["desc"]], key=lambda r: r["gate"])
        undescribed = sorted([r for r in fam_rows if not r["desc"]], key=lambda r: r["gate"])
        out.append(f"## {f}\n")
        out.append(f"{desc}. {len(described)} of {len(fam_rows)} described.\n")
        for r in described:
            d = r["desc"]
            name = r["gate"].split("/")[-1]
            out.append(f"### `{name}` — {r['kind']}, {r['tier']}\n")
            out.append(f"**WHAT:** {safe(d['WHAT'])}\n")
            out.append(f"**HOW:** {safe(d['HOW'])}\n")
            out.append(f"**EXPECTS:** {safe(d['EXPECTS'])}\n")
        if undescribed:
            out.append("**Not yet described:** " + ", ".join(f"`{r['gate'].split('/')[-1]}`" for r in undescribed) + ".\n")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(REPO))
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    root = Path(a.root).resolve()
    rows, problems = collect(root)
    for p in problems:
        print("PROBLEM " + p)
    text = render(rows)
    dst = root / OUT
    nd = sum(1 for r in rows if r["desc"])
    if a.check:
        cur = dst.read_text(encoding="utf-8") if dst.exists() else ""
        if cur != text:
            print(f"STALE {OUT} differs from a regeneration:")
            for line in list(difflib.unified_diff(cur.splitlines(), text.splitlines(),
                                                  "committed", "regenerated", lineterm=""))[:40]:
                print("  " + line)
            return 1
        if problems:
            return 1
        print(f"ok    {OUT} is current ({nd} of {len(rows)} gates described)")
        return 0
    dst.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({nd} of {len(rows)} gates described; {len(problems)} problems)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
