#!/usr/bin/env python3
"""gen_annotations.py — docs/annotations.md, the address -> label/comment
STREAM, is GENERATED from every carrier the tree already has.

  python3 tools/gen_annotations.py            # rewrite docs/annotations.md
  python3 tools/gen_annotations.py --check    # regenerate, cmp, diff on drift
  python3 tools/gen_annotations.py --root DIR # a copy of the tree (controls)
  python3 tools/gen_annotations.py --stats    # the coverage figures only

WHY THIS EXISTS (14z-123, the documentation rationalization pass, the T1
"annotations check" the maintainer ruled at the 14z-122 close). CLAUDE.md
Section 5 had promised `docs/annotations.md` — "raw address -> label/comment
stream" — since M0, and the file was never created; 14z-122 retired the row
with the note that the stream "lives in the atlas and the manifests' inline
comments". MEASURED at 14z-123, that note was wrong: the tree names ~3,100
distinct program-space addresses, `engine_internals.md` alone names ~600 of
which ~220 appear in NO other document, and ~260 more are known only to
gate scripts and tools. `re/ghidra/` never held a project (a `.keep` and an
M0 README). So the stream exists, scattered across five kinds of carrier,
and the maintainer's ruling for that case was CREATE IT — but a sixth
hand-written copy would drift (the project's own doctrine), so the document
is generated from the carriers and gated current, the GOTCHAS-index pattern.

WHAT AN ENTRY IS. Every program-space address (`PRG:0x..`, `CPU:$..`, or a
bare 5-6 digit `0x..` inside `0x001000-0x3FFFFF`) named in a carrier, with
the carrier FILE and the SECTION (`##`/`###` header) it sits under, or for a
manifest the nearest preceding `name = "..."` / `[[table]]`. NO LINE
NUMBERS on purpose: line numbers churn on every unrelated doc edit and would
turn the currency gate into a tax on every commit; file + section is what a
reader greps anyway. A game hint (vs2 / vh2) is attached when the address's
own line names the sibling set before the address; unmarked means vsavj or
unspecified — the docs mix the three address spaces and this index does not
pretend to disambiguate what the sentence did not.

WHAT IS EXCLUDED, and why. RAM addresses: `docs/game/atlas/ram.md` IS the
RAM stream by construction (one row per address). Object/record OFFSETS
(`+0x1C`) are not addresses. HIST/EXEMPT/GENERATED-classed docs
(`docs/doc_shape.tsv`): superseded records are not live carriers, and a
generated file citing generated files is a loop. `build/manifest/probe_*.toml`:
rig fixtures cloned from the tenant manifests, every address a duplicate.
The tail section, CODE-ONLY ADDRESSES, lists what tools and gates name that
no document or manifest does — that list is the documentation gap the pass
works down, kept visible rather than hidden.

Some rows are not addresses (a `0x40000` region SIZE looks like one). They
are kept: the section column shows what they are, and a heuristic that
guessed would hide real rows to hide noise.
ROM-free, emulator-free, ~1 s (ci_portable, tests/test_annotations_current.sh).
"""
import argparse
import collections
import difflib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = "docs/annotations.md"
SHAPE = "docs/doc_shape.tsv"
LO, HI = 0x001000, 0x3FFFFF

ADDR_RE = re.compile(r"(?:PRG:0x|CPU:\$|\b0x)0*([0-9A-Fa-f]{5,6})\b")
HDR_RE = re.compile(r"^(#{1,3})\s+(.*?)\s*$")
ANCHOR_RE = re.compile(r"\*\*\[[A-Z]+-\d+\]\*\*\s*")
NAME_RE = re.compile(r'^\s*name\s*=\s*"([^"]*)"')
TABLE_RE = re.compile(r"^\s*\[\[?([A-Za-z0-9_.]+)\]?\]\s*$")
GAME_RE = re.compile(r"\b(vsav2|vs2|vhunt2|vh2|vsavj|vsav)\b", re.I)

# (tier, glob, kind) — the tier orders carriers in a row; kind picks the labeller.
CARRIERS = [
    (0, "docs/game/atlas/*.md", "doc"),
    (1, "docs/game/engine_internals.md", "doc"),
    (2, "docs/game/*.md", "doc"),
    (2, "docs/platform/*.md", "doc"),
    (2, "docs/project/*.md", "doc"),
    (2, "docs/project/tables/*.md", "doc"),
    (2, "HANDOFF.md", "doc"),
    (3, "build/manifest/*.toml", "toml"),
    (4, "tools/*.py", "code"),
    (4, "tools/*.sh", "code"),
    (4, "tests/*.sh", "code"),
    (4, "tests/lib/*.sh", "code"),
    (4, "tests/lua/*.lua", "code"),
]
CODE_TIER = 4
# the generator and its gate name synthetic control addresses — not carriers
SELF = {"tools/gen_annotations.py", "tests/test_annotations_current.sh"}
MAX_CARRIERS = 6

PREAMBLE = """\
# annotations — the address -> label/comment stream (GENERATED)

<!-- generated by tools/gen_annotations.py — do not edit; regenerate -->

**STATUS: GENERATED (14z-123).** Every program-space address the tree
names, with WHERE it is named — carrier file and the section (or manifest
row name) it sits under. Regenerate with `python3 tools/gen_annotations.py`;
`tests/test_annotations_current.sh` fails when this file is stale.

This is an INDEX, not a source: the fact lives in the carrier, and the
carrier is what a `grep` of the address reaches. Rows are sorted by
address; the `where` column lists carriers in tier order — the atlas
(`docs/game/atlas/`), then `engine_internals.md`, then the other
documents, then `build/manifest/*.toml`, then code (`tools/`, `tests/`).
A `vs2`/`vh2` hint marks a line that named the sibling set before the
address; unmarked is vsavj or unspecified. Addresses named ONLY by code
are listed in the last section — that list is the documentation gap.

RAM addresses are not here: `docs/game/atlas/ram.md` is the RAM stream
(one row per address). Address notation is CLAUDE.md Section 5's.
"""


def shape_excluded(root):
    """Docs classed HIST/EXEMPT/GENERATED are not live carriers."""
    out = set()
    p = root / SHAPE
    if not p.exists():
        return out
    for line in p.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        cells = line.split("\t")
        if len(cells) >= 2 and cells[1] in ("HIST", "EXEMPT", "GENERATED"):
            out.add(cells[0])
    out.add(OUT)
    return out


def game_hint(line, end):
    """The sibling-set token nearest BEFORE the address on its own line."""
    last = None
    for m in GAME_RE.finditer(line[:end]):
        last = m.group(1).lower()
    if last in ("vsav2", "vs2"):
        return "vs2"
    if last in ("vhunt2", "vh2"):
        return "vh2"
    return ""


def scan_doc(text):
    """Yield (addr, section, hint) for a markdown carrier."""
    section = "(top)"
    fence = False
    for line in text.splitlines():
        if line.startswith("```"):
            fence = not fence
        m = HDR_RE.match(line)
        if m and not fence:
            section = ANCHOR_RE.sub("", m.group(2)).strip()
            section = re.sub(r"\s+", " ", section)
        for am in ADDR_RE.finditer(line):
            v = int(am.group(1), 16)
            if LO <= v <= HI:
                yield v, section, game_hint(line, am.start())


def scan_toml(text):
    """Yield (addr, label, hint): label = nearest `name =` else `[[table]]`."""
    table = "(top)"
    label = None
    for line in text.splitlines():
        m = TABLE_RE.match(line)
        if m:
            table, label = m.group(1), None
        m = NAME_RE.match(line)
        if m:
            label = m.group(1)
        for am in ADDR_RE.finditer(line):
            v = int(am.group(1), 16)
            if LO <= v <= HI:
                yield v, (label or table), game_hint(line, am.start())


def collect(root):
    """addr -> {(tier, relpath, section, hint)}; also the per-tier sets."""
    excluded = shape_excluded(root)
    rows = collections.defaultdict(set)
    seen_files = set()
    for tier, pattern, kind in CARRIERS:
        for p in sorted(root.glob(pattern)):
            rel = p.relative_to(root).as_posix()
            if rel in excluded or rel in seen_files or rel in SELF:
                continue
            if rel.endswith("_history.md") or rel.endswith("_HISTORY.md"):
                continue
            if kind == "toml" and p.name.startswith("probe_"):
                continue
            seen_files.add(rel)
            try:
                text = p.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            if kind == "doc":
                for v, sec, hint in scan_doc(text):
                    rows[v].add((tier, rel, sec, hint))
            elif kind == "toml":
                for v, lab, hint in scan_toml(text):
                    rows[v].add((tier, rel, lab, hint))
            else:
                for am in ADDR_RE.finditer(text):
                    v = int(am.group(1), 16)
                    if LO <= v <= HI:
                        rows[v].add((tier, rel, "", ""))
    return rows


def stats(rows):
    doc_only = code_only = both = 0
    by_tier = collections.Counter()
    for v, carriers in rows.items():
        tiers = {t for t, _, _, _ in carriers}
        for t in tiers:
            by_tier[t] += 1
        if tiers == {CODE_TIER}:
            code_only += 1
        elif CODE_TIER in tiers:
            both += 1
        else:
            doc_only += 1
    return {"total": len(rows), "doc_only": doc_only, "code_only": code_only,
            "doc_and_code": both, "by_tier": dict(sorted(by_tier.items()))}


def cell(s):
    return s.replace("|", "\\|").replace("`", "'")


def render(rows):
    out = [PREAMBLE]
    st = stats(rows)
    tier_names = {0: "atlas", 1: "engine_internals", 2: "other docs",
                  3: "manifests", 4: "code"}
    out.append("## Coverage\n")
    out.append("| figure | count |\n|---|---|")
    out.append(f"| distinct program-space addresses named | {st['total']} |")
    out.append(f"| named by a document or manifest only | {st['doc_only']} |")
    out.append(f"| named by both a document/manifest and code | {st['doc_and_code']} |")
    out.append(f"| named by CODE ONLY (the gap list below) | {st['code_only']} |")
    for t, n in st["by_tier"].items():
        out.append(f"| carried by {tier_names[t]} | {n} |")
    out.append("")
    out.append("## Addresses\n")
    out.append("| address | where named (tier order; file — section) |\n|---|---|")
    gap = []
    for v in sorted(rows):
        carriers = sorted(rows[v])
        tiers = {t for t, _, _, _ in carriers}
        if tiers == {CODE_TIER}:
            gap.append((v, sorted({rel for _, rel, _, _ in carriers})))
            continue
        # documents and manifests, deduped by (file, section); code files by name only
        parts = []
        seen = set()
        for t, rel, sec, hint in carriers:
            if t == CODE_TIER:
                key = ("code", rel)
                txt = rel
            else:
                key = (rel, sec)
                txt = f"{rel} — {sec}" if sec else rel
            if hint:
                txt += f" [{hint}]"
                key = key + (hint,)
            if key in seen:
                continue
            seen.add(key)
            parts.append(txt)
        shown = parts[:MAX_CARRIERS]
        more = len(parts) - len(shown)
        where = "; ".join(cell(p) for p in shown)
        if more > 0:
            where += f"; +{more} more"
        out.append(f"| `PRG:0x{v:06X}` | {where} |")
    out.append("")
    out.append("## Code-only addresses (the documentation gap)\n")
    out.append("Named by a tool, gate or Lua instrument and by NO document or "
               "manifest. A row leaves this list when a carrier above names "
               "the address.\n")
    out.append("| address | files |\n|---|---|")
    for v, files in gap:
        shown = files[:MAX_CARRIERS]
        more = len(files) - len(shown)
        where = "; ".join(cell(f) for f in shown)
        if more > 0:
            where += f"; +{more} more"
        out.append(f"| `PRG:0x{v:06X}` | {where} |")
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(REPO))
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--stats", action="store_true")
    a = ap.parse_args()
    root = Path(a.root).resolve()
    rows = collect(root)
    if a.stats:
        for k, v in stats(rows).items():
            print(f"{k}: {v}")
        return 0
    text = render(rows)
    dst = root / OUT
    if a.check:
        cur = dst.read_text(encoding="utf-8") if dst.exists() else ""
        if cur == text:
            print(f"ok    {OUT} is current ({stats(rows)['total']} addresses)")
            return 0
        print(f"STALE {OUT} differs from a regeneration:")
        for line in list(difflib.unified_diff(cur.splitlines(), text.splitlines(),
                                              "committed", "regenerated", lineterm=""))[:40]:
            print("  " + line)
        return 1
    dst.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({stats(rows)['total']} addresses)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
