#!/usr/bin/env python3
"""gen_gate_index.py — docs/project/gate_index.md, THE GATE INDEX, is GENERATED.

  python3 tools/gen_gate_index.py            # rewrite docs/project/gate_index.md
  python3 tools/gen_gate_index.py --check    # regenerate, cmp, diff on drift
  python3 tools/gen_gate_index.py --root DIR # a copy of the tree (controls)

WHY THIS EXISTS (14z-123, the documentation rationalization pass, G6). HANDOFF
carried a 2,160-line hand-written fence of `tests/x.sh   # comment` lines —
168 of the 281 scripts under tests/, 113 unindexed, one duplicated, and each
comment a session narrative that the script's own header often lacked. The
maintainer ruled that a gate's WHY lives in the gate script's header; this
index is what a reader opens INSTEAD of the fence, and it cannot go stale:
every row is derived from the tree, and the gate `tests/test_gate_index_current.sh`
fails when the committed file differs from a regeneration.

WHAT A ROW IS. One per `tests/*.sh` script:
  gate    — the script
  kind    — test (a PASS/FAIL gate) / audit (an on-demand measurement with a
            frozen expectation) / run (a runner)
  tier    — ci_portable / ci_static (from tests/ci_portable.txt, ci_static.txt)
            / emulator (needs MAME, FBNeo or the simulator — never in CI)
  family  — hand-assigned in tests/gate_index.tsv (the ONE hand-maintained
            input: `gate<TAB>family[<TAB>needs][<TAB>since]`); completeness is
            enforced both ways — a new script without a row, or a row whose
            script is gone, fails --check
  needs   — the TSV override, else derived: portable = nothing; static =
            ROMDIR; emulator = the instruments its header names (MAME, FBNeo,
            Verilator/sim, a build dir) + the first "~N min/s" it quotes
  locks   — the script header's own first sentence(s), up to ~240 chars: the
            text after `# name.sh — ` until a blank `#` line, cut at a
            sentence end. The header is the source of truth; if a row reads
            badly, fix the header, not this tool.
  since   — the TSV override, else the first session token (14z-N / M2a /
            session N / a date) the header quotes
Rows are grouped by family, sorted by name. ROM-free, ~0.2 s.
"""
import argparse
import difflib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = "docs/project/gate_index.md"
TSV = "tests/gate_index.tsv"
FAMILIES = [
    ("runner", "the suite runners and their own ground truth"),
    ("docs", "the documentation locks — docs, skills, indexes, tables follow the tree"),
    ("platform", "the emulators and the ROM images as instruments — builds, decrypt, replay determinism, harness hygiene"),
    ("pipeline", "the build pipeline — manifests, patch ops, extraction/reconciliation/generation law, static censuses"),
    ("oracle", "the CLAUDE.md §4 oracle classes — masked legacy, flicker/window/composite, dual-track, the recording corpus"),
    ("gfx", "tiles, OBJ records, sprite lists, render-layer verdicts"),
    ("tenant", "tenant content — per-character gates and on-demand audits on the ported characters"),
    ("character-data", "the character-data map — move naming, hitboxes, reactions, projectiles, measured mechanics"),
    ("review-triage", "the 14z-94 adversarial-review closures (GitHub #74's index) — every one a guard the review asked for"),
    ("mister", "the MiSTer lane — the jtcps2w core, the simulation oracles, MRA/.rom generation"),
]
FAM_NAMES = [f for f, _ in FAMILIES]
SESSION_RE = re.compile(r"\b(14z-\d+[a-z]?(?:\s*\(\d+\))?|M[0-9][a-z]?\b|session \d+[a-z]?|20\d\d-\d\d-\d\d)")
MIN_RE = re.compile(r"~\s*(\d+(?:\.\d+)?)\s*(min|s\b|sec|h\b|hours?)")

PREAMBLE = """\
# The gate index (GENERATED)

<!-- generated by tools/gen_gate_index.py — do not edit; regenerate -->

**STATUS: GENERATED (14z-123).** One row per script under `tests/`, grouped by
family. The `locks` column is each script's OWN header sentence — the header
is the source of truth (the 14z-123 ruling: a gate's WHY lives in the gate);
`family` comes from `tests/gate_index.tsv`, the one hand-maintained input;
`tier` from `tests/ci_portable.txt` / `tests/ci_static.txt`. Regenerate with
`python3 tools/gen_gate_index.py`; `tests/test_gate_index_current.sh` fails
when this file is stale or a script has no family row.

**How to run things** is HANDOFF.md "How to test": the portable tier is
`tests/run_all_static.sh` (ROM-free, ~1 min), `ROMDIR=... tests/run_all_static.sh
--strict` adds the static tier and makes SKIP fatal; emulator-tier gates and
audits are run by name with the `needs` shown here. HANDOFF's former per-gate
fence (as of 14z-123) is verbatim in `HANDOFF_HISTORY.md`.
"""


def read_tsv(root):
    rows = {}
    p = root / TSV
    if not p.exists():
        return rows
    for line in p.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        c = line.split("\t")
        rows[c[0]] = {"family": c[1] if len(c) > 1 else "",
                      "needs": c[2] if len(c) > 2 else "",
                      "since": c[3] if len(c) > 3 else ""}
    return rows


def registries(root):
    def names(f):
        p = root / "tests" / f
        if not p.exists():
            return set()
        return {l.strip() for l in p.read_text(encoding="utf-8").splitlines()
                if l.strip() and not l.startswith("#")}
    return names("ci_portable.txt"), names("ci_static.txt")


def header_text(path, whole=False):
    """The comment block after the shebang: the first paragraph (up to the
    first blank `#` line) for `locks`, or the WHOLE block for `needs`."""
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    out = []
    for l in lines[1:120]:
        if not l.startswith("#"):
            break
        t = l.lstrip("#").strip()
        if not t and out and not whole:
            break
        if t:
            out.append(t)
    return " ".join(out)


def locks_sentence(name, head):
    t = re.sub(r"^" + re.escape(name) + r"\s*[—–-]+\s*", "", head)
    t = re.sub(r"\s+", " ", t).strip()
    if len(t) <= 240:
        return t
    cut = t[:240]
    m = max(cut.rfind(". "), cut.rfind("; "), cut.rfind(": "))
    if m > 120:
        return cut[:m + 1].rstrip()
    return cut.rstrip() + "…"


def derive_needs(tier, head):
    if tier == "ci_portable":
        return "—"
    if tier == "ci_static":
        return "ROMDIR"
    inst = []
    h = head.lower()
    for key, label in (("verilator", "Verilator"), ("jtsim", "Verilator"), ("simulator", "Verilator"),
                       ("mame", "MAME"), ("fbneo", "FBNeo")):
        if key in h and label not in inst:
            inst.append(label)
    if re.search(r"build/\w|build dir|builddir|<build>", h):
        inst.append("a build dir")
    m = MIN_RE.search(head)
    dur = f"~{m.group(1)} {m.group(2)}" if m else ""
    return ", ".join(inst + ([dur] if dur else [])) or "emulator"


def derive_since(head):
    m = SESSION_RE.search(head)
    return m.group(1) if m else "—"


def collect(root):
    tsv = read_tsv(root)
    port, stat = registries(root)
    scripts = sorted(p for p in (root / "tests").glob("*.sh"))
    rows, problems = [], []
    seen = set()
    for p in scripts:
        gate = "tests/" + p.name
        seen.add(gate)
        head = header_text(p)
        whole = header_text(p, whole=True)
        tier = "ci_portable" if p.stem in port else "ci_static" if p.stem in stat else "emulator"
        t = tsv.get(gate)
        if t is None:
            problems.append(f"NO FAMILY ROW in {TSV}: {gate}")
            fam = "?"
            needs = since = ""
        else:
            fam, needs, since = t["family"], t["needs"], t["since"]
            if fam not in FAM_NAMES:
                problems.append(f"UNKNOWN FAMILY {fam!r} for {gate}")
        kind = "audit" if p.name.startswith("audit_") else "run" if p.name.startswith("run_") else "test"
        rows.append({"gate": gate, "kind": kind, "tier": tier, "family": fam,
                     "needs": needs or derive_needs(tier, whole),
                     "locks": locks_sentence(p.name, head) or "(no header sentence — write one)",
                     "since": since or derive_since(whole)})
    for gate in tsv:
        if gate not in seen:
            problems.append(f"DEAD ROW in {TSV}: {gate} (script gone)")
    return rows, problems


def cell(s):
    return s.replace("|", "\\|")


def render(rows):
    out = [PREAMBLE]
    n = len(rows)
    tiers = {t: sum(1 for r in rows if r["tier"] == t) for t in ("ci_portable", "ci_static", "emulator")}
    out.append(f"**{n} scripts** — {tiers['ci_portable']} ci_portable, {tiers['ci_static']} ci_static, "
               f"{tiers['emulator']} emulator-tier (run by name).\n")
    out.append("| family | scripts | what the family is |\n|---|---|---|")
    for f, desc in FAMILIES:
        out.append(f"| [{f}](#{f}) | {sum(1 for r in rows if r['family'] == f)} | {desc} |")
    out.append("")
    for f, desc in FAMILIES:
        fam_rows = [r for r in rows if r["family"] == f]
        if not fam_rows:
            continue
        out.append(f"## {f}\n")
        out.append(f"{desc}.\n")
        out.append("| gate | kind | tier | needs | locks (the script's own header) | since |\n|---|---|---|---|---|---|")
        for r in sorted(fam_rows, key=lambda r: r["gate"]):
            out.append(f"| `{r['gate']}` | {r['kind']} | {r['tier']} | {cell(r['needs'])} | {cell(r['locks'])} | {cell(r['since'])} |")
        out.append("")
    unk = [r for r in rows if r["family"] not in FAM_NAMES]
    if unk:
        out.append("## UNASSIGNED (fix tests/gate_index.tsv)\n")
        out.append("| gate | tier |\n|---|---|")
        for r in unk:
            out.append(f"| `{r['gate']}` | {r['tier']} |")
        out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(REPO))
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    root = Path(a.root).resolve()
    rows, problems = collect(root)
    for p in problems:
        print("PROBLEM " + p)
    text = render(rows)
    dst = root / OUT
    if a.check:
        cur = dst.read_text(encoding="utf-8") if dst.exists() else ""
        if cur != text:
            print(f"STALE {OUT} differs from a regeneration:")
            for line in list(difflib.unified_diff(cur.splitlines(), text.splitlines(),
                                                  "committed", "regenerated", lineterm=""))[:40]:
                print("  " + line)
            return 1
        if problems:
            return 1
        print(f"ok    {OUT} is current ({len(rows)} scripts, every one with a family)")
        return 0
    dst.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(rows)} scripts; {len(problems)} problems)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
