#!/usr/bin/env python3
"""gen_gotchas_index.py — docs/GOTCHAS.md is GENERATED from the three buckets.

  python3 tools/gen_gotchas_index.py            # rewrite docs/GOTCHAS.md
  python3 tools/gen_gotchas_index.py --check    # regenerate, cmp, diff on drift
  python3 tools/gen_gotchas_index.py --root DIR # a copy of the tree (controls)

WHY THIS EXISTS (14z-122, the documentation rationalization pass). The index
was hand-maintained: ten "### appended 14z-N" session digests had grown
between the routing table and the body, the body itself was a THIRD
hand-abridged copy of the bucket entries (the bullets did not match the
bucket headers), and the desync had already happened once — a 14z-118 entry
records an index line missing while the bucket entry existed. An index that
is generated cannot desync; the old hand-written content lives verbatim in
docs/GOTCHAS_history.md.

WHAT AN ENTRY IS: every `## ` header of the three bucket files, with two
normalizations — CONSECUTIVE `## ` lines merge into one entry (the buckets
wrap long headers as a second `## ` line), and `**[PFX-N]**` anchor tokens
are stripped. Everything else (the `(paid: 14z-N)` cost tags included) is
kept verbatim, so a grep that hits the index hits the bucket. No per-entry
links on purpose: a hand-derived slug that stops resolving is worse than a
bucket-file link that always does.
ROM-free, emulator-free, ~0.1 s (ci_portable, tests/test_gotchas_index_current.sh).
"""
import argparse
import difflib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = "docs/GOTCHAS.md"
BUCKETS = [("Game — Vampire Savior", "docs/game/gotchas.md", "game/gotchas.md"),
           ("Platform — CPS-2, MAME, FBNeo", "docs/platform/gotchas.md", "platform/gotchas.md"),
           ("Project — our pipeline and method", "docs/project/gotchas.md", "project/gotchas.md")]
ANCHOR_RE = re.compile(r"\*\*\[[A-Z]+-\d+\]\*\*\s*")

PREAMBLE = """\
# GOTCHAS — index

<!-- generated by tools/gen_gotchas_index.py — do not edit; regenerate -->

The entries live in three files, split 2026-08-08 by one question:
**would this still be true if we abandoned the roster hack tomorrow?**

| file | what is in it |
|---|---|
| [`game/gotchas.md`](game/gotchas.md) | Vampire Savior itself — engine behaviour, data layout, modes that fail quietly |
| [`platform/gotchas.md`](platform/gotchas.md) | CPS-2 hardware/encryption + MAME and FBNeo behaviour and builds |
| [`project/gotchas.md`](project/gotchas.md) | our pipeline, harness, gates, manifests and method |

**Appending a new one:** put it in the file its FACT belongs to, not the
one your current task belongs to. A trap you hit while porting Huitzil
is a GAME gotcha if it is true of the game regardless of the port. Then
regenerate this index: `python3 tools/gen_gotchas_index.py`.

This index is ONE LINE PER BUCKET ENTRY, generated (14z-122) — the
hand-written index it replaced, including the per-session digests it had
accreted, is verbatim in [`GOTCHAS_history.md`](GOTCHAS_history.md).
"""


def entries(text):
    """The bucket's `## ` headers, consecutive ones merged, anchors stripped."""
    out = []
    prev_header = False
    for line in text.splitlines():
        m = re.match(r"^## (.*)$", line)
        if m:
            part = ANCHOR_RE.sub("", m.group(1)).strip()
            if prev_header and out:
                out[-1] = (out[-1] + " " + part).strip()
            else:
                out.append(part)
            prev_header = True
        else:
            prev_header = False
    return [re.sub(r"\s+", " ", e) for e in out]


def render(root):
    parts = [PREAMBLE]
    counts = []
    for title, rel, link in BUCKETS:
        es = entries((root / rel).read_text(encoding="utf-8", errors="replace"))
        counts.append(len(es))
        parts.append(f"\n## {title} ([`{link}`]({link})) — {len(es)} entries\n\n")
        parts.append("\n".join(f"- {e}" for e in es) + "\n")
    total = sum(counts)
    parts.insert(1, f"\n{total} entries ({counts[0]} game / {counts[1]} platform / "
                    f"{counts[2]} project), counted from the buckets at generation.\n")
    return "".join(parts)


SYN = "## first entry\nbody\n\n## a long entry that wraps (14z-1,\n## and this is its second line)\nbody\n"


def selftests():
    bad = []
    got = entries(SYN)
    if got != ["first entry", "a long entry that wraps (14z-1, and this is its second line)"]:
        bad.append(f"entry extractor drifted: {got}")
    if entries("## a **[VSP-9]** anchored entry\n") != ["a anchored entry"]:
        bad.append("anchor token not stripped")
    return bad


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", default=str(REPO))
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--no-selftest", action="store_true")
    a = ap.parse_args()
    root = Path(a.root)
    fails = [] if a.no_selftest else [f"SELF-TEST: {b}" for b in selftests()]
    want = render(root)
    out = root / OUT
    if a.check:
        have = out.read_text() if out.is_file() else ""
        if have != want:
            diff = difflib.unified_diff(have.splitlines(), want.splitlines(),
                                        "committed", "regenerated", lineterm="", n=0)
            lines = [d for d in diff if not d.startswith(("---", "+++", "@@"))]
            fails.append("docs/GOTCHAS.md DRIFTED from the buckets — regenerate:\n      "
                         + "\n      ".join(lines[:30]))
    else:
        out.write_text(want)
        print(f"wrote {OUT} ({len(want.splitlines())} lines)")
    if fails:
        for f in fails:
            print(f"  FAIL  {f}")
        sys.exit(1)
    if a.check:
        print("ALL PASS (docs/GOTCHAS.md matches a regeneration from the three buckets)")


if __name__ == "__main__":
    main()
