#!/usr/bin/env python3
"""wheel_positions.py — measure where each select-wheel cell IS on screen.

The ROM's wheel record and its coordinate list give 18 OBJ entries in
DRAWING order, which is not cell order, so positions cannot be assigned to
cells statically. They can be measured: park the cursor on each cell and
read the cursor ring out of OBJ RAM. The ring is palette 0x1E
(docs/GOTCHAS.md, the 14z-49 medallion-identification lesson), which is the
handle that makes this cheap.

Two modes:

  --tour <out.rpl>      generate a replay that visits all 16 navigable
                        cells and parks on each, plus the DUMPS spec and
                        the park/cell table (as JSON on stdout)
  --extract <dumpdir>   read the OBJ-RAM dumps that run produced and print
                        the cell -> screen-centre map

Usage:
  wheel_positions.py --data <vsavj_data.bin> --tour /tmp/tour.rpl
  wheel_positions.py --meta /tmp/tour.json --extract <dir> [--json out]

Entry format is CPS-2 OBJ: X.w, Y.w, tile.w, attr.w; the list ENDS at the
first entry whose y-word has bit 15 set (CpsObjGet), and everything past
that terminator is stale (docs/GOTCHAS.md) — so the walk must respect it.
Coordinates carry bank/control bits above bit 9; mask to 10 bits.
"""

import argparse
import json
import struct
import sys

# TABLE B's address and column labelling come from select_wheel.wheel_facts
# (GitHub #48): this tool used to restate both as literals with no --set
# argument, so pointed at a vsav2 image it would silently have read TABLE B
# at vsavj's address. wheel_facts also runs the KNOWN_PATHS ground truth
# (vsavj), so a wrong direction labelling REFUSES here instead of emitting
# a tour replay with permuted stick directions.
import select_wheel as _sw

NDIR = _sw.NDIR
DEFAULT_CELL = _sw.DEFAULT_CELL          # Demitri, same pin as select_wheel
OBJ_BASE = 0x708000
OBJ_LEN = 0x1000
CURSOR_PAL = 0x1E


def load_rows(data_path, set_name):
    """First 16 TABLE B rows (the live half) + the validated column names."""
    dat = open(data_path, "rb").read()
    cfg, rows, order = _sw.wheel_facts(dat, set_name)
    return rows[:16], {d: n for d, n in enumerate(order)}


def route(rows, src, dst):
    seen, q = {src: []}, [src]
    while q:
        nxt = []
        for c in q:
            for dd in range(NDIR):
                v = rows[c][dd]
                if v not in seen:
                    seen[v] = seen[c] + [dd]
                    if v == dst:
                        return seen[v]
                    nxt.append(v)
        q = nxt
    return None


def make_tour(rows, names, start_frame=900, step=3, park=40, settle=25):
    cur, frame, lines, parks = DEFAULT_CELL, start_frame, [], []
    order = [DEFAULT_CELL] + [c for c in range(16) if c != DEFAULT_CELL]
    for tgt in order:
        if tgt != cur:
            r = route(rows, cur, tgt)
            if r is None:
                raise SystemExit("cell %02X is unreachable" % tgt)
            for dd in r:
                lines.append("%d p1=%s" % (frame, names[dd]))
                frame += step
            cur = tgt
        parks.append({"cell": cur, "dump_frame": frame + settle})
        frame += park
    return lines, parks, frame + 30


def extract(dumpdir, parks):
    out = {}
    for p in parks:
        path = "%s/dump_%d_%06x.bin" % (dumpdir, p["dump_frame"], OBJ_BASE)
        d = open(path, "rb").read()
        ring = []
        for i in range(0, len(d), 8):
            x, y, _t, a = struct.unpack(">HHHH", d[i:i + 8])
            if y & 0x8000:          # sprite-list terminator
                break
            if (a & 0x1F) == CURSOR_PAL:
                ring.append((x & 0x3FF, y & 0x3FF))
        if not ring:
            raise SystemExit("cell %02X: no palette-0x%02X sprites in %s"
                             % (p["cell"], CURSOR_PAL, path))
        xs = [e[0] for e in ring]
        ys = [e[1] for e in ring]
        out[p["cell"]] = ((min(xs) + max(xs)) // 2, (min(ys) + max(ys)) // 2,
                          len(ring))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", help="DATA-space image (for --tour)")
    ap.add_argument("--tour", help="write the tour replay here")
    ap.add_argument("--meta", help="tour metadata JSON (written by --tour)")
    ap.add_argument("--extract", help="directory holding the OBJ-RAM dumps")
    ap.add_argument("--json", help="write the measured positions here")
    ap.add_argument("--set", default="vsavj", choices=sorted(_sw.SETS),
                    help="which game's tables to read (GitHub #48: was "
                         "hardcoded vsavj)")
    args = ap.parse_args()

    if args.tour:
        rows, names = load_rows(args.data, args.set)
        lines, parks, last = make_tour(rows, names)
        with open(args.tour, "w") as f:
            f.write("# GENERATED by tools/wheel_positions.py — do not "
                    "hand-edit.\n# Parks the cursor on all 16 navigable "
                    "cells so the ring can be read from OBJ RAM.\n")
            f.write("300-305 sys=C1\n800-803 sys=S1\n")
            f.write("\n".join(lines) + "\n%d wait\n" % last)
        meta = {"parks": parks, "frames": last,
                "dumps": ";".join("%d:%06x-%06x" % (p["dump_frame"], OBJ_BASE,
                                                    OBJ_BASE + OBJ_LEN)
                                  for p in parks)}
        if args.meta:
            json.dump(meta, open(args.meta, "w"), indent=1)
        print(json.dumps(meta))
        return 0

    if args.extract:
        meta = json.load(open(args.meta))
        pos = extract(args.extract, meta["parks"])
        print("cell -> screen centre of the palette-0x1E cursor ring:")
        for c in sorted(pos):
            x, y, n = pos[c]
            print("  cell %02X: (%3d, %3d)   [%d ring sprites]" % (c, x, y, n))
        if args.json:
            json.dump({"%02X" % c: pos[c][:2] for c in pos},
                      open(args.json, "w"), indent=1)
        return 0

    ap.error("give --tour or --extract")


if __name__ == "__main__":
    sys.exit(main())
